<?php

namespace DocConverter\Parser\DocxParser\Math;

/**
 * Latex math symbols container
 */
class MathSymbols {

    const ARGUMENT_PLACEHOLDER = "{%@xarg@%}";

    /* commands */
    public static $commands = [
        "subscript" => "_{" . self::ARGUMENT_PLACEHOLDER . "}",
        "superscript" => "^{" . self::ARGUMENT_PLACEHOLDER . "}",
        "fraction" => "\\frac{" . self::ARGUMENT_PLACEHOLDER . "}{" . self::ARGUMENT_PLACEHOLDER . "}",
        "text" => "\\text{" . self::ARGUMENT_PLACEHOLDER . "}",
        "matrix" => "\\begin{matrix} " . self::ARGUMENT_PLACEHOLDER . " \\end{matrix}",
        "array" => "\\begin{array}{c} " . self::ARGUMENT_PLACEHOLDER . " \\end{array}",
        "box" => "\\boxed{" . self::ARGUMENT_PLACEHOLDER . "}",
        "accent" => "\\accentset{" . self::ARGUMENT_PLACEHOLDER . "}{" . self::ARGUMENT_PLACEHOLDER . "}",
        "substack" => "\\substack{" . self::ARGUMENT_PLACEHOLDER . "}",
        "overtext" => "\\overset{" . self::ARGUMENT_PLACEHOLDER . "}{" . self::ARGUMENT_PLACEHOLDER . "}",
    ];

    /* functions */
    public static $functions = [
        "sqrt" => "\\sqrt{" . self::ARGUMENT_PLACEHOLDER . "}",
        "sqrt_deg" => "\\sqrt[%xarg%]{" . self::ARGUMENT_PLACEHOLDER . "}",
        "arccos" => "\\arccos ",
        "arcsin" => "\\arcsin ",
        "arctan" => "\\arctan ",
        "arg" => "\\arg ",
        "cos" => "\\cos ",
        "cosh" => "\\arccosh ",
        "cot" => "\\cot ",
        "coth" => "\\coth ",
        "arcsin" => "\\arcsin ",
        "csc" => "\\csc ",
        "deg" => "\\deg ",
        "det" => "\\det ",
        "dim" => "\\dim ",
        "exp" => "\\exp ",
        "gcd" => "\\gcd ",
        "hom" => "\\hom ",
        "inf" => "\\inf ",
        "ker" => "\\ker ",
        "lg" => "\\lg ",
        "lim" => "\\lim ",
        "liminf" => "\\liminf ",
        "limsup" => "\\limsup ",
        "ln" => "\\ln ",
        "log" => "\\log ",
        "max" => "\\max ",
        "min" => "\\min ",
        "Pr" => "\\Pr ",
        "sec" => "\\sec ",
        "sin" => "\\sin ",
        "sinh" => "\\sinh ",
        "sup" => "\\sup ",
        "tan" => "\\tan ",
        "tanh" => "\\tanh ",
    ];

    /* general symbols */
    public static $symbols = [
        "\u{00021}" => "!", // ! 
        "\u{00023}" => "\\# ", // # 
        "\u{00024}" => "\\$ ", // $ 
        "\u{00025}" => "\\% ", // % 
        "\u{00026}" => "\\& ", // & 
        "\u{00028}" => "(", // ( 
        "\u{00029}" => ")", // ) 
        "\u{0002A}" => "*", // * 
        "\u{0002B}" => "+", // + 
        "\u{0002C}" => ",", // , 
        "\u{0002E}" => ".", // . 
        "\u{0002F}" => "/", // / 
        "\u{00031}" => "1", // 1 
        "\u{00032}" => "2", // 2 
        "\u{00033}" => "3", // 3 
        "\u{00034}" => "4", // 4 
        "\u{00035}" => "5", // 5 
        "\u{00036}" => "6", // 6 
        "\u{00037}" => "7", // 7 
        "\u{00038}" => "8", // 8 
        "\u{00039}" => "9", // 9 
        "\u{0003A}" => ":", // : 
        "\u{0003B}" => ";", // ; 
        "\u{0003C}" => "<", // < 
        "\u{0003D}" => "=", // = 
        "\u{0003E}" => ">", // > 
        "\u{0003F}" => "?", // ? 
        "\u{00040}" => "@", // @ 
        "\u{00041}" => "A", // A 
        "\u{00042}" => "B", // B 
        "\u{00043}" => "C", // C 
        "\u{00044}" => "D", // D 
        "\u{00045}" => "E", // E 
        "\u{00046}" => "F", // F 
        "\u{00047}" => "G", // G 
        "\u{00048}" => "H", // H 
        "\u{00049}" => "I", // I 
        "\u{0004A}" => "J", // J 
        "\u{0004B}" => "K", // K 
        "\u{0004C}" => "L", // L 
        "\u{0004D}" => "M", // M 
        "\u{0004E}" => "N", // N 
        "\u{0004F}" => "O", // O 
        "\u{00050}" => "P", // P 
        "\u{00051}" => "Q", // Q 
        "\u{00052}" => "R", // R 
        "\u{00053}" => "S", // S 
        "\u{00054}" => "T", // T 
        "\u{00055}" => "U", // U 
        "\u{00056}" => "V", // V 
        "\u{00057}" => "W", // W 
        "\u{00058}" => "X", // X 
        "\u{00059}" => "Y", // Y 
        "\u{0005A}" => "Z", // Z 
        "\u{0005B}" => "\\lbrack ", // [ 
        "\u{0005C}" => "\\backslash ", // \ 
        "\u{0005D}" => "\\rbrack ", // ] 
        "\u{0005E}" => "\\sphat ", // 
        "\u{0005F}" => "\\_ ", // _ 
        "\u{00061}" => "a", // a 
        "\u{00062}" => "b", // b 
        "\u{00063}" => "c", // c 
        "\u{00064}" => "d", // d 
        "\u{00065}" => "e", // e 
        "\u{00066}" => "f", // f 
        "\u{00067}" => "g", // g 
        "\u{00068}" => "h", // h 
        "\u{00069}" => "i", // i 
        "\u{0006A}" => "j", // j 
        "\u{0006B}" => "k", // k 
        "\u{0006C}" => "l", // l 
        "\u{0006D}" => "m", // m 
        "\u{0006E}" => "n", // n 
        "\u{0006F}" => "o", // o 
        "\u{00070}" => "p", // p 
        "\u{00071}" => "q", // q 
        "\u{00072}" => "r", // r 
        "\u{00073}" => "s", // s 
        "\u{00074}" => "t", // t 
        "\u{00075}" => "u", // u 
        "\u{00076}" => "v", // v 
        "\u{00077}" => "w", // w 
        "\u{00078}" => "x", // x 
        "\u{00079}" => "y", // y 
        "\u{0007A}" => "z", // z 
        "\u{0007B}" => "\\{", // { 
        "\u{0007C}" => "|", // | 
        "\u{0007D}" => "\\}", // } 
        "\u{0007E}" => "\\sptilde ", // ~ 
        "\u{000A0}" => "~", //   
        "\u{000A2}" => "\\cent ", // ¢ 
        "\u{000A3}" => "\\pounds ", // £ 
        "\u{000A5}" => "\\yen ", // ¥ 
        "\u{000A8}" => "\\spddot ", // ¨ 
        "\u{000AC}" => "\\neg ", // ¬ 
        "\u{000AE}" => "\\circledR ", // ® 
        "\u{000B1}" => "\\pm ", // ± 
        "\u{000B5}" => "\\Micro ", // µ 
        "\u{000D7}" => "\\times ", // × 
        "\u{000F0}" => "\\eth ", // ð 
        "\u{000F7}" => "\\div ", // ÷ 
        "\u{00131}" => "\\imath ", // ı 
        "\u{00237}" => "\\jmath ", // ȷ 
        "\u{00300}" => "\\grave ", // x̀ 
        "\u{00301}" => "\\acute ", // x́ 
        "\u{00302}" => "\\hat ", // x̂ 
        "\u{00303}" => "\\tilde ", // x̃ 
        "\u{00304}" => "\\bar ", // x̄ 
        "\u{00305}" => "\\overline ", // x̅ 
        "\u{00306}" => "\\breve ", // x̆ 
        "\u{00307}" => "\\dot ", // ẋ 
        "\u{00308}" => "\\ddot ", // ẍ 
        "\u{0030A}" => "\\mathring ", // x̊ 
        "\u{0030C}" => "\\check ", // x̌ 
        "\u{00330}" => "\\utilde ", // x̰ 
        "\u{00331}" => "\\underbar ", // x̱ 
        "\u{00332}" => "\\underline ", // x̲ 
        "\u{00338}" => "\\not ", // x̸ 
        "\u{00393}" => "\\Gamma ", // Γ 
        "\u{00394}" => "\\Delta ", // Δ 
        "\u{00398}" => "\\Theta ", // Θ 
        "\u{0039B}" => "\\Lambda ", // Λ 
        "\u{0039E}" => "\\Xi ", // Ξ 
        "\u{003A0}" => "\\Pi ", // Π 
        "\u{003A3}" => "\\Sigma ", // Σ 
        "\u{003A5}" => "\\Upsilon ", // Υ 
        "\u{003A6}" => "\\Phi ", // Φ 
        "\u{003A8}" => "\\Psi ", // Ψ 
        "\u{003A9}" => "\\Omega ", // Ω 
        "\u{003B1}" => "\\alpha ", // α 
        "\u{003B2}" => "\\beta ", // β 
        "\u{003B3}" => "\\gamma ", // γ 
        "\u{003B4}" => "\\delta ", // δ 
        "\u{003B5}" => "\\varepsilon ", // ε 
        "\u{003B6}" => "\\zeta ", // ζ 
        "\u{003B7}" => "\\eta ", // η 
        "\u{003B8}" => "\\theta ", // θ 
        "\u{003B9}" => "\\iota ", // ι 
        "\u{003BA}" => "\\kappa ", // κ 
        "\u{003BB}" => "\\lambda ", // λ 
        "\u{003BC}" => "\\mu ", // μ 
        "\u{003BD}" => "\\nu ", // ν 
        "\u{003BE}" => "\\xi ", // ξ 
        "\u{003C0}" => "\\pi ", // π 
        "\u{003C1}" => "\\rho ", // ρ 
        "\u{003C2}" => "\\varsigma ", // ς 
        "\u{003C3}" => "\\sigma ", // σ 
        "\u{003C4}" => "\\tau ", // τ 
        "\u{003C5}" => "\\upsilon ", // υ 
        "\u{003C6}" => "\\varphi ", // φ 
        "\u{003C7}" => "\\chi ", // χ 
        "\u{003C8}" => "\\psi ", // ψ 
        "\u{003C9}" => "\\omega ", // ω 
        "\u{003D0}" => "\\varbeta ", // ϐ 
        "\u{003D1}" => "\\vartheta ", // ϑ 
        "\u{003D5}" => "\\phi ", // ϕ 
        "\u{003D6}" => "\\varpi ", // ϖ 
        "\u{003D8}" => "\\Qoppa ", // Ϙ 
        "\u{003D9}" => "\\qoppa ", // ϙ 
        "\u{003DA}" => "\\Stigma ", // Ϛ 
        "\u{003DB}" => "\\stigma ", // ϛ 
        "\u{003DC}" => "\\Digamma ", // Ϝ 
        "\u{003DD}" => "\\digamma ", // ϝ 
        "\u{003DE}" => "\\Koppa ", // Ϟ 
        "\u{003DF}" => "\\koppa ", // ϟ 
        "\u{003E0}" => "\\Sampi ", // Ϡ 
        "\u{003E1}" => "\\sampi ", // ϡ 
        "\u{003F1}" => "\\varrho ", // ϱ 
        "\u{003F5}" => "\\epsilon ", // ϵ 
        "\u{003F6}" => "\\backepsilon ", // ϶ 
        "\u{02001}" => "\\quad ", //   
        "\u{02016}" => "\\| ", // ‖ 
        "\u{02020}" => "\\dagger ", // † 
        "\u{02021}" => "\\ddagger ", // ‡ 
        "\u{02026}" => "\\ldots ", // … 
        "\u{02032}" => "\\prime ", // ′ 
        "\u{02033}" => "\\second ", // ″ 
        "\u{02034}" => "\\third ", // ‴ 
        "\u{02035}" => "\\backprime ", // ‵ 
        "\u{02040}" => "\\cat ", // ⁀ 
        "\u{02057}" => "\\fourth ", // ⁗ 
        "\u{0205F}" => "\\: ", //   
        "\u{020D0}" => "\\lvec ", // x⃐ 
        "\u{020D1}" => "\\vec ", // x⃑ 
        "\u{020D6}" => "\\LVec ", // x⃖ 
        "\u{020D7}" => "\\vec ", // x⃗ 
        "\u{020DB}" => "\\dddot ", // x⃛ 
        "\u{020DC}" => "\\ddddot ", // x⃜ 
        "\u{020E1}" => "\\overleftrightarrow ", // x⃡ 
        "\u{020EE}" => "\\underleftarrow ", // x⃮ 
        "\u{020EF}" => "\\underrightarrow ", // x⃯ 
        "\u{02102}" => "\\mathbb{C} ", // ℂ 
        "\u{02107}" => "\\Euler ", // ℇ 
        "\u{0210A}" => "\\mathcal{g} ", // ℊ 
        "\u{0210B}" => "\\mathcal{H} ", // ℋ 
        "\u{0210C}" => "\\mathfrak{H} ", // ℌ 
        "\u{0210D}" => "\\mathbb{H} ", // ℍ 
        "\u{0210F}" => "\\hslash ", // ℏ 
        "\u{02110}" => "\\mathcal{I} ", // ℐ 
        "\u{02111}" => "\\Im ", // ℑ 
        "\u{02112}" => "\\mathcal{L} ", // ℒ 
        "\u{02113}" => "\\ell ", // ℓ 
        "\u{02115}" => "\\mathbb{N} ", // ℕ 
        "\u{02118}" => "\\wp ", // ℘ 
        "\u{02119}" => "\\mathbb{P} ", // ℙ 
        "\u{0211A}" => "\\mathbb{Q} ", // ℚ 
        "\u{0211B}" => "\\mathcal{R} ", // ℛ 
        "\u{0211C}" => "\\Re ", // ℜ 
        "\u{0211D}" => "\\mathbb{R} ", // ℝ 
        "\u{02124}" => "\\mathbb{Z} ", // ℤ 
        "\u{02126}" => "\\tcohm ", // Ω 
        "\u{02127}" => "\\mho ", // ℧ 
        "\u{02128}" => "\\mathfrak{Z} ", // ℨ 
        "\u{0212B}" => "\\Angstroem ", // Å 
        "\u{0212C}" => "\\mathcal{B} ", // ℬ 
        "\u{0212D}" => "\\mathfrak{C} ", // ℭ 
        "\u{0212F}" => "\\mathcal{e} ", // ℯ 
        "\u{02130}" => "\\mathcal{E} ", // ℰ 
        "\u{02131}" => "\\mathcal{F} ", // ℱ 
        "\u{02132}" => "\\Finv ", // Ⅎ 
        "\u{02133}" => "\\mathcal{M} ", // ℳ 
        "\u{02134}" => "\\mathcal{o} ", // ℴ 
        "\u{02135}" => "\\aleph ", // ℵ 
        "\u{02136}" => "\\beth ", // ℶ 
        "\u{02137}" => "\\gimel ", // ℷ 
        "\u{02138}" => "\\daleth ", // ℸ 
        "\u{0213C}" => "\\mathbb{\pi} ", // ℼ 
        "\u{0213D}" => "\\mathbb{\gamma} ", // ℽ 
        "\u{0213E}" => "\\mathbb{\Gamma} ", // ℾ 
        "\u{0213F}" => "\\mathbb{\Pi} ", // ℿ 
        "\u{02140}" => "\\mathbb{\Sigma} ", // ⅀ 
        "\u{02144}" => "\\Yup ", // ⅄ 
        "\u{02145}" => "\\CapitalDifferentialD ", // ⅅ 
        "\u{02146}" => "\\DifferentialD ", // ⅆ 
        "\u{02147}" => "\\ExponetialE ", // ⅇ 
        "\u{02148}" => "\\ComplexI ", // ⅈ 
        "\u{02149}" => "\\ComplexJ ", // ⅉ 
        "\u{0214B}" => "\\invamp ", // ⅋ 
        "\u{02190}" => "\\leftarrow ", // ← 
        "\u{02191}" => "\\uparrow ", // ↑ 
        "\u{02192}" => "\\rightarrow ", // → 
        "\u{02193}" => "\\downarrow ", // ↓ 
        "\u{02194}" => "\\leftrightarrow ", // ↔ 
        "\u{02195}" => "\\updownarrow ", // ↕ 
        "\u{02196}" => "\\nwarrow ", // ↖ 
        "\u{02197}" => "\\nearrow ", // ↗ 
        "\u{02198}" => "\\searrow ", // ↘ 
        "\u{02199}" => "\\swarrow ", // ↙ 
        "\u{0219A}" => "\\nleftarrow ", // ↚ 
        "\u{0219B}" => "\\nrightarrow ", // ↛ 
        "\u{0219E}" => "\\twoheadleftarrow ", // ↞ 
        "\u{021A0}" => "\\twoheadrightarrow ", // ↠ 
        "\u{021A2}" => "\\leftarrowtail ", // ↢ 
        "\u{021A3}" => "\\rightarrowtail ", // ↣ 
        "\u{021A4}" => "\\mapsfrom ", // ↤ 
        "\u{021A5}" => "\\MapsUp ", // ↥ 
        "\u{021A6}" => "\\mapsto ", // ↦ 
        "\u{021A7}" => "\\MapsDown ", // ↧ 
        "\u{021A9}" => "\\hookleftarrow ", // ↩ 
        "\u{021AA}" => "\\hookrightarrow ", // ↪ 
        "\u{021AB}" => "\\looparrowleft ", // ↫ 
        "\u{021AC}" => "\\looparrowright ", // ↬ 
        "\u{021AD}" => "\\leftrightsquigarrow ", // ↭ 
        "\u{021AE}" => "\\nleftrightarrow ", // ↮ 
        "\u{021AF}" => "\\lightning ", // ↯ 
        "\u{021B0}" => "\\Lsh ", // ↰ 
        "\u{021B1}" => "\\Rsh ", // ↱ 
        "\u{021B2}" => "\\dlsh ", // ↲ 
        "\u{021B3}" => "\\drsh ", // ↳ 
        "\u{021B6}" => "\\curvearrowleft ", // ↶ 
        "\u{021B7}" => "\\curvearrowright ", // ↷ 
        "\u{021BA}" => "\\circlearrowleft ", // ↺ 
        "\u{021BB}" => "\\circlearrowright ", // ↻ 
        "\u{021BC}" => "\\leftharpoonup ", // ↼ 
        "\u{021BD}" => "\\leftharpoondown ", // ↽ 
        "\u{021BE}" => "\\upharpoonright ", // ↾ 
        "\u{021BF}" => "\\upharpoonleft ", // ↿ 
        "\u{021C0}" => "\\rightharpoonup ", // ⇀ 
        "\u{021C1}" => "\\rightharpoondown ", // ⇁ 
        "\u{021C2}" => "\\downharpoonright ", // ⇂ 
        "\u{021C3}" => "\\downharpoonleft ", // ⇃ 
        "\u{021C4}" => "\\rightleftarrows ", // ⇄ 
        "\u{021C5}" => "\\updownarrows ", // ⇅ 
        "\u{021C6}" => "\\leftrightarrows ", // ⇆ 
        "\u{021C7}" => "\\leftleftarrows ", // ⇇ 
        "\u{021C8}" => "\\upuparrows ", // ⇈ 
        "\u{021C9}" => "\\rightrightarrows ", // ⇉ 
        "\u{021CA}" => "\\downdownarrows ", // ⇊ 
        "\u{021CB}" => "\\leftrightharpoons ", // ⇋ 
        "\u{021CC}" => "\\rightleftharpoons ", // ⇌ 
        "\u{021CD}" => "\\nLeftarrow ", // ⇍ 
        "\u{021CE}" => "\\nLeftrightarrow ", // ⇎ 
        "\u{021CF}" => "\\nRightarrow ", // ⇏ 
        "\u{021D0}" => "\\Leftarrow ", // ⇐ 
        "\u{021D1}" => "\\Uparrow ", // ⇑ 
        "\u{021D2}" => "\\Rightarrow ", // ⇒ 
        "\u{021D3}" => "\\Downarrow ", // ⇓ 
        "\u{021D4}" => "\\Leftrightarrow ", // ⇔ 
        "\u{021D5}" => "\\Updownarrow ", // ⇕ 
        "\u{021D6}" => "\\Nwarrow ", // ⇖ 
        "\u{021D7}" => "\\Nearrow ", // ⇗ 
        "\u{021D8}" => "\\Searrow ", // ⇘ 
        "\u{021D9}" => "\\Swarrow ", // ⇙ 
        "\u{021DA}" => "\\Lleftarrow ", // ⇚ 
        "\u{021DB}" => "\\Rrightarrow ", // ⇛ 
        "\u{021DC}" => "\\leftsquigarrow ", // ⇜ 
        "\u{021DD}" => "\\rightsquigarrow ", // ⇝ 
        "\u{021E0}" => "\\dashleftarrow ", // ⇠ 
        "\u{021E2}" => "\\dashrightarrow ", // ⇢ 
        "\u{021E4}" => "\\LeftArrowBar ", // ⇤ 
        "\u{021E5}" => "\\RightArrowBar ", // ⇥ 
        "\u{021F5}" => "\\downuparrows ", // ⇵ 
        "\u{021F8}" => "\\pfun ", // ⇸ 
        "\u{021FB}" => "\\ffun ", // ⇻ 
        "\u{021FD}" => "\\leftarrowtriangle ", // ⇽ 
        "\u{021FE}" => "\\rightarrowtriangle ", // ⇾ 
        "\u{021FF}" => "\\leftrightarrowtriangle ", // ⇿ 
        "\u{02200}" => "\\forall ", // ∀ 
        "\u{02201}" => "\\complement ", // ∁ 
        "\u{02202}" => "\\partial ", // ∂ 
        "\u{02203}" => "\\exists ", // ∃ 
        "\u{02204}" => "\\nexists ", // ∄ 
        "\u{02205}" => "\\varnothing ", // ∅ 
        "\u{02207}" => "\\nabla ", // ∇ 
        "\u{02208}" => "\\in ", // ∈ 
        "\u{02209}" => "\\notin ", // ∉ 
        "\u{0220B}" => "\\ni ", // ∋ 
        "\u{0220C}" => "\\nni ", // ∌ 
        "\u{0220F}" => "\\prod ", // ∏ 
        "\u{02210}" => "\\coprod ", // ∐ 
        "\u{02211}" => "\\sum ", // ∑ 
        "\u{02212}" => "-", // − 
        "\u{02213}" => "\\mp ", // ∓ 
        "\u{02214}" => "\\dotplus ", // ∔ 
        "\u{02215}" => "\\slash ", // ∕ 
        "\u{02216}" => "\\smallsetminus ", // ∖ 
        "\u{02217}" => "\\ast ", // ∗ 
        "\u{02218}" => "\\circ ", // ∘ 
        "\u{02219}" => "\\bullet ", // ∙ 
        "\u{0221A}" => "\\sqrt ", // √ 
        "\u{0221B}" => "\\sqrt[3] ", // ∛ 
        "\u{0221C}" => "\\sqrt[4] ", // ∜ 
        "\u{0221D}" => "\\propto ", // ∝ 
        "\u{0221E}" => "\\infty ", // ∞ 
        "\u{0221F}" => "\\rightangle ", // ∟ 
        "\u{02220}" => "\\angle ", // ∠ 
        "\u{02221}" => "\\measuredangle ", // ∡ 
        "\u{02222}" => "\\sphericalangle ", // ∢ 
        "\u{02223}" => "\\mid ", // ∣ 
        "\u{02224}" => "\\nmid ", // ∤ 
        "\u{02225}" => "\\parallel ", // ∥ 
        "\u{02226}" => "\\nparallel ", // ∦ 
        "\u{02227}" => "\\wedge ", // ∧ 
        "\u{02228}" => "\\vee ", // ∨ 
        "\u{02229}" => "\\cap ", // ∩ 
        "\u{0222A}" => "\\cup ", // ∪ 
        "\u{0222B}" => "\\int ", // ∫ 
        "\u{0222C}" => "\\iint ", // ∬ 
        "\u{0222D}" => "\\iiint ", // ∭ 
        "\u{0222E}" => "\\oint ", // ∮ 
        "\u{0222F}" => "\\oiint ", // ∯ 
        "\u{02230}" => "\\oiiint ", // ∰ 
        "\u{02232}" => "\\varointclockwise ", // ∲ 
        "\u{02233}" => "\\ointctrclockwise ", // ∳ 
        "\u{02234}" => "\\therefore ", // ∴ 
        "\u{02235}" => "\\because ", // ∵ 
        "\u{02236}" => ":", // ∶ 
        "\u{02237}" => "\\Proportion ", // ∷ 
        "\u{02239}" => "\\eqcolon ", // ∹ 
        "\u{0223C}" => "\\sim ", // ∼ 
        "\u{0223D}" => "\\backsim ", // ∽ 
        "\u{0223F}" => "\\AC ", // ∿ 
        "\u{02240}" => "\\wr ", // ≀ 
        "\u{02241}" => "\\nsim ", // ≁ 
        "\u{02242}" => "\\eqsim ", // ≂ 
        "\u{02243}" => "\\simeq ", // ≃ 
        "\u{02244}" => "\\nsimeq ", // ≄ 
        "\u{02245}" => "\\cong ", // ≅ 
        "\u{02247}" => "\\ncong ", // ≇ 
        "\u{02248}" => "\\approx ", // ≈ 
        "\u{02249}" => "\\napprox ", // ≉ 
        "\u{0224A}" => "\\approxeq ", // ≊ 
        "\u{0224D}" => "\\asymp ", // ≍ 
        "\u{0224E}" => "\\Bumpeq ", // ≎ 
        "\u{0224F}" => "\\bumpeq ", // ≏ 
        "\u{02250}" => "\\doteq ", // ≐ 
        "\u{02251}" => "\\Doteq ", // ≑ 
        "\u{02252}" => "\\fallingdotseq ", // ≒ 
        "\u{02253}" => "\\risingdotseq ", // ≓ 
        "\u{02254}" => "\\coloneq ", // ≔ 
        "\u{02255}" => "\\eqcolon ", // ≕ 
        "\u{02256}" => "\\eqcirc ", // ≖ 
        "\u{02257}" => "\\circeq ", // ≗ 
        "\u{02259}" => "\\corresponds ", // ≙ 
        "\u{0225C}" => "\\triangleq ", // ≜ 
        "\u{02260}" => "\\neq ", // ≠ 
        "\u{02261}" => "\\equiv ", // ≡ 
        "\u{02262}" => "\\nequiv ", // ≢ 
        "\u{02264}" => "\\leq ", // ≤ 
        "\u{02265}" => "\\geq ", // ≥ 
        "\u{02266}" => "\\leqq ", // ≦ 
        "\u{02267}" => "\\geqq ", // ≧ 
        "\u{02268}" => "\\lneqq ", // ≨ 
        "\u{02269}" => "\\gneqq ", // ≩ 
        "\u{0226A}" => "\\ll ", // ≪ 
        "\u{0226B}" => "\\gg ", // ≫ 
        "\u{0226C}" => "\\between ", // ≬ 
        "\u{0226D}" => "\\notasymp ", // ≭ 
        "\u{0226E}" => "\\nless ", // ≮ 
        "\u{0226F}" => "\\ngtr ", // ≯ 
        "\u{02270}" => "\\nleq ", // ≰ 
        "\u{02271}" => "\\ngeq ", // ≱ 
        "\u{02272}" => "\\lesssim ", // ≲ 
        "\u{02273}" => "\\gtrsim ", // ≳ 
        "\u{02274}" => "\\NotLessTilde ", // ≴ 
        "\u{02275}" => "\\NotGreaterTilde ", // ≵ 
        "\u{02276}" => "\\lessgtr ", // ≶ 
        "\u{02277}" => "\\gtrless ", // ≷ 
        "\u{02279}" => "\\NotGreaterLess ", // ≹ 
        "\u{0227A}" => "\\prec ", // ≺ 
        "\u{0227B}" => "\\succ ", // ≻ 
        "\u{0227C}" => "\\preccurlyeq ", // ≼ 
        "\u{0227D}" => "\\succcurlyeq ", // ≽ 
        "\u{0227E}" => "\\precsim ", // ≾ 
        "\u{0227F}" => "\\succsim ", // ≿ 
        "\u{02280}" => "\\nprec ", // ⊀ 
        "\u{02281}" => "\\nsucc ", // ⊁ 
        "\u{02282}" => "\\subset ", // ⊂ 
        "\u{02283}" => "\\supset ", // ⊃ 
        "\u{02284}" => "\\nsubset ", // ⊄ 
        "\u{02285}" => "\\nsupset ", // ⊅ 
        "\u{02286}" => "\\subseteq ", // ⊆ 
        "\u{02287}" => "\\supseteq ", // ⊇ 
        "\u{02288}" => "\\nsubseteq ", // ⊈ 
        "\u{02289}" => "\\nsupseteq ", // ⊉ 
        "\u{0228A}" => "\\subsetneq ", // ⊊ 
        "\u{0228B}" => "\\supsetneq ", // ⊋ 
        "\u{0228E}" => "\\uplus ", // ⊎ 
        "\u{0228F}" => "\\sqsubset ", // ⊏ 
        "\u{02290}" => "\\sqsupset ", // ⊐ 
        "\u{02291}" => "\\sqsubseteq ", // ⊑ 
        "\u{02292}" => "\\sqsupseteq ", // ⊒ 
        "\u{02293}" => "\\sqcap ", // ⊓ 
        "\u{02294}" => "\\sqcup ", // ⊔ 
        "\u{02295}" => "\\oplus ", // ⊕ 
        "\u{02296}" => "\\ominus ", // ⊖ 
        "\u{02297}" => "\\otimes ", // ⊗ 
        "\u{02298}" => "\\oslash ", // ⊘ 
        "\u{02299}" => "\\odot ", // ⊙ 
        "\u{0229A}" => "\\circledcirc ", // ⊚ 
        "\u{0229B}" => "\\circledast ", // ⊛ 
        "\u{0229D}" => "\\circleddash ", // ⊝ 
        "\u{0229E}" => "\\boxplus ", // ⊞ 
        "\u{0229F}" => "\\boxminus ", // ⊟ 
        "\u{022A0}" => "\\boxtimes ", // ⊠ 
        "\u{022A1}" => "\\boxdot ", // ⊡ 
        "\u{022A2}" => "\\vdash ", // ⊢ 
        "\u{022A3}" => "\\dashv ", // ⊣ 
        "\u{022A4}" => "\\top ", // ⊤ 
        "\u{022A5}" => "\\bot ", // ⊥ 
        "\u{022A7}" => "\\models ", // ⊧ 
        "\u{022A8}" => "\\vDash ", // ⊨ 
        "\u{022A9}" => "\\Vdash ", // ⊩ 
        "\u{022AA}" => "\\Vvdash ", // ⊪ 
        "\u{022AB}" => "\\VDash ", // ⊫ 
        "\u{022AC}" => "\\nvdash ", // ⊬ 
        "\u{022AD}" => "\\nvDash ", // ⊭ 
        "\u{022AE}" => "\\nVdash ", // ⊮ 
        "\u{022AF}" => "\\nVDash ", // ⊯ 
        "\u{022B2}" => "\\vartriangleleft ", // ⊲ 
        "\u{022B3}" => "\\vartriangleright ", // ⊳ 
        "\u{022B4}" => "\\trianglelefteq ", // ⊴ 
        "\u{022B5}" => "\\trianglerighteq ", // ⊵ 
        "\u{022B6}" => "\\multimapdotbothA ", // ⊶ 
        "\u{022B7}" => "\\multimapdotbothB ", // ⊷ 
        "\u{022B8}" => "\\multimap ", // ⊸ 
        "\u{022BA}" => "\\intercal ", // ⊺ 
        "\u{022BB}" => "\\veebar ", // ⊻ 
        "\u{022BC}" => "\\barwedge ", // ⊼ 
        "\u{022C0}" => "\\bigwedge ", // ⋀ 
        "\u{022C1}" => "\\bigvee ", // ⋁ 
        "\u{022C2}" => "\\bigcap ", // ⋂ 
        "\u{022C3}" => "\\bigcup ", // ⋃ 
        "\u{022C4}" => "\\diamond ", // ⋄ 
        "\u{022C5}" => "\\cdot ", // ⋅ 
        "\u{022C6}" => "\\star ", // ⋆ 
        "\u{022C7}" => "\\divideontimes ", // ⋇ 
        "\u{022C8}" => "\\bowtie ", // ⋈ 
        "\u{022C9}" => "\\ltimes ", // ⋉ 
        "\u{022CA}" => "\\rtimes ", // ⋊ 
        "\u{022CB}" => "\\leftthreetimes ", // ⋋ 
        "\u{022CC}" => "\\rightthreetimes ", // ⋌ 
        "\u{022CD}" => "\\backsimeq ", // ⋍ 
        "\u{022CE}" => "\\curlyvee ", // ⋎ 
        "\u{022CF}" => "\\curlywedge ", // ⋏ 
        "\u{022D0}" => "\\Subset ", // ⋐ 
        "\u{022D1}" => "\\Supset ", // ⋑ 
        "\u{022D2}" => "\\Cap ", // ⋒ 
        "\u{022D3}" => "\\Cup ", // ⋓ 
        "\u{022D4}" => "\\pitchfork ", // ⋔ 
        "\u{022D5}" => "\\hash ", // ⋕ 
        "\u{022D6}" => "\\lessdot ", // ⋖ 
        "\u{022D7}" => "\\gtrdot ", // ⋗ 
        "\u{022D8}" => "\\lll ", // ⋘ 
        "\u{022D9}" => "\\ggg ", // ⋙ 
        "\u{022DA}" => "\\lesseqgtr ", // ⋚ 
        "\u{022DB}" => "\\gtreqless ", // ⋛ 
        "\u{022DE}" => "\\curlyeqprec ", // ⋞ 
        "\u{022DF}" => "\\curlyeqsucc ", // ⋟ 
        "\u{022E0}" => "\\npreceq ", // ⋠ 
        "\u{022E1}" => "\\nsucceq ", // ⋡ 
        "\u{022E2}" => "\\nsqsubseteq ", // ⋢ 
        "\u{022E3}" => "\\nsqsupseteq ", // ⋣ 
        "\u{022E6}" => "\\lnsim ", // ⋦ 
        "\u{022E7}" => "\\gnsim ", // ⋧ 
        "\u{022E8}" => "\\precnsim ", // ⋨ 
        "\u{022E9}" => "\\succnsim ", // ⋩ 
        "\u{022EA}" => "\\ntriangleleft ", // ⋪ 
        "\u{022EB}" => "\\ntriangleright ", // ⋫ 
        "\u{022EC}" => "\\ntrianglelefteq ", // ⋬ 
        "\u{022ED}" => "\\ntrianglerighteq ", // ⋭ 
        "\u{022EE}" => "\\vdots ", // ⋮ 
        "\u{022EF}" => "\\cdots ", // ⋯ 
        "\u{022F0}" => "\\iddots ", // ⋰ 
        "\u{022F1}" => "\\ddots ", // ⋱ 
        "\u{022F6}" => "\\barin ", // ⋶ 
        "\u{02300}" => "\\diameter ", // ⌀ 
        "\u{02308}" => "\\lceil ", // ⌈ 
        "\u{02309}" => "\\rceil ", // ⌉ 
        "\u{0230A}" => "\\lfloor ", // ⌊ 
        "\u{0230B}" => "\\rfloor ", // ⌋ 
        "\u{02310}" => "\\invneg ", // ⌐ 
        "\u{02311}" => "\\wasylozenge ", // ⌑ 
        "\u{0231C}" => "\\ulcorner ", // ⌜ 
        "\u{0231D}" => "\\urcorner ", // ⌝ 
        "\u{0231E}" => "\\llcorner ", // ⌞ 
        "\u{0231F}" => "\\lrcorner ", // ⌟ 
        "\u{02322}" => "\\frown ", // ⌢ 
        "\u{02323}" => "\\smile ", // ⌣ 
        "\u{02339}" => "\\APLinv ", // ⌹ 
        "\u{0233F}" => "\\notslash ", // ⌿ 
        "\u{02340}" => "\\notbackslash ", // ⍀ 
        "\u{02347}" => "\\APLleftarrowbox ", // ⍇ 
        "\u{02348}" => "\\APLrightarrowbox ", // ⍈ 
        "\u{02350}" => "\\APLuparrowbox ", // ⍐ 
        "\u{02357}" => "\\APLdownarrowbox ", // ⍗ 
        "\u{0235D}" => "\\APLcomment ", // ⍝ 
        "\u{0235E}" => "\\APLinput ", // ⍞ 
        "\u{0235F}" => "\\APLlog ", // ⍟ 
        "\u{023DC}" => "\\overparen ", // ⏜ 
        "\u{023DD}" => "\\underparen ", // ⏝ 
        "\u{023DE}" => "\\overbrace ", // ⏞ 
        "\u{023DF}" => "\\underbrace ", // ⏟ 
        "\u{025B3}" => "\\bigtriangleup ", // △ 
        "\u{025B4}" => "\\blacktriangleup ", // ▴ 
        "\u{025B5}" => "\\smalltriangleup ", // ▵ 
        "\u{025B6}" => "\\RHD ", // ▶ 
        "\u{025B7}" => "\\rhd ", // ▷ 
        "\u{025B8}" => "\\blacktriangleright ", // ▸ 
        "\u{025B9}" => "\\smalltriangleright ", // ▹ 
        "\u{025BD}" => "\\bigtriangledown ", // ▽ 
        "\u{025BE}" => "\\blacktriangledown ", // ▾ 
        "\u{025BF}" => "\\smalltriangledown ", // ▿ 
        "\u{025C0}" => "\\LHD ", // ◀ 
        "\u{025C1}" => "\\lhd ", // ◁ 
        "\u{025C2}" => "\\blacktriangleleft ", // ◂ 
        "\u{025C3}" => "\\smalltriangleleft ", // ◃ 
        "\u{025C6}" => "\\Diamondblack ", // ◆ 
        "\u{025C7}" => "\\Diamond ", // ◇ 
        "\u{025CA}" => "\\lozenge ", // ◊ 
        "\u{025CB}" => "\\Circle ", // ○ 
        "\u{025CF}" => "\\CIRCLE ", // ● 
        "\u{025D0}" => "\\LEFTcircle ", // ◐ 
        "\u{025D1}" => "\\RIGHTcircle ", // ◑ 
        "\u{025D6}" => "\\LEFTCIRCLE ", // ◖ 
        "\u{025D7}" => "\\RIGHTCIRCLE ", // ◗ 
        "\u{025EB}" => "\\boxbar ", // ◫ 
        "\u{025FB}" => "\\square ", // ◻ 
        "\u{025FC}" => "\\blacksquare ", // ◼ 
        "\u{02605}" => "\\bigstar ", // ★ 
        "\u{02609}" => "\\Sun ", // ☉ 
        "\u{02610}" => "\\Square ", // ☐ 
        "\u{02611}" => "\\CheckedBox ", // ☑ 
        "\u{02612}" => "\\XBox ", // ☒ 
        "\u{02615}" => "\\steaming ", // ☕ 
        "\u{0261E}" => "\\pointright ", // ☞ 
        "\u{02620}" => "\\skull ", // ☠ 
        "\u{02622}" => "\\radiation ", // ☢ 
        "\u{02623}" => "\\biohazard ", // ☣ 
        "\u{0262F}" => "\\yinyang ", // ☯ 
        "\u{02639}" => "\\frownie ", // ☹ 
        "\u{0263A}" => "\\smiley ", // ☺ 
        "\u{0263B}" => "\\blacksmiley ", // ☻ 
        "\u{0263C}" => "\\sun ", // ☼ 
        "\u{0263D}" => "\\rightmoon ", // ☽ 
        "\u{0263E}" => "\\leftmoon ", // ☾ 
        "\u{0263F}" => "\\mercury ", // ☿ 
        "\u{02640}" => "\\female ", // ♀ 
        "\u{02641}" => "\\earth ", // ♁ 
        "\u{02642}" => "\\male ", // ♂ 
        "\u{02643}" => "\\jupiter ", // ♃ 
        "\u{02644}" => "\\saturn ", // ♄ 
        "\u{02645}" => "\\uranus ", // ♅ 
        "\u{02646}" => "\\neptune ", // ♆ 
        "\u{02647}" => "\\pluto ", // ♇ 
        "\u{02648}" => "\\aries ", // ♈ 
        "\u{02649}" => "\\taurus ", // ♉ 
        "\u{0264A}" => "\\gemini ", // ♊ 
        "\u{0264B}" => "\\cancer ", // ♋ 
        "\u{0264C}" => "\\leo ", // ♌ 
        "\u{0264D}" => "\\virgo ", // ♍ 
        "\u{0264E}" => "\\libra ", // ♎ 
        "\u{0264F}" => "\\scorpio ", // ♏ 
        "\u{02650}" => "\\sagittarius ", // ♐ 
        "\u{02651}" => "\\capricornus ", // ♑ 
        "\u{02652}" => "\\aquarius ", // ♒ 
        "\u{02653}" => "\\pisces ", // ♓ 
        "\u{02660}" => "\\spadesuit ", // ♠ 
        "\u{02661}" => "\\heartsuit ", // ♡ 
        "\u{02662}" => "\\diamondsuit ", // ♢ 
        "\u{02663}" => "\\clubsuit ", // ♣ 
        "\u{02664}" => "\\varspadesuit ", // ♤ 
        "\u{02665}" => "\\varheartsuit ", // ♥ 
        "\u{02666}" => "\\vardiamondsuit ", // ♦ 
        "\u{02667}" => "\\varclubsuit ", // ♧ 
        "\u{02669}" => "\\quarternote ", // ♩ 
        "\u{0266A}" => "\\eighthnote ", // ♪ 
        "\u{0266B}" => "\\twonotes ", // ♫ 
        "\u{0266C}" => "\\sixteenthnote ", // ♬ 
        "\u{0266D}" => "\\flat ", // ♭ 
        "\u{0266E}" => "\\natural ", // ♮ 
        "\u{0266F}" => "\\sharp ", // ♯ 
        "\u{0267B}" => "\\recycle ", // ♻ 
        "\u{02693}" => "\\anchor ", // ⚓ 
        "\u{02694}" => "\\swords ", // ⚔ 
        "\u{026A0}" => "\\warning ", // ⚠ 
        "\u{026AA}" => "\\medcirc ", // ⚪ 
        "\u{026AB}" => "\\medbullet ", // ⚫ 
        "\u{0270E}" => "\\pencil ", // ✎ 
        "\u{02713}" => "\\checkmark ", // ✓ 
        "\u{02717}" => "\\ballotx ", // ✗ 
        "\u{02720}" => "\\maltese ", // ✠ 
        "\u{027A2}" => "\\arrowbullet ", // ➢ 
        "\u{027C2}" => "\\perp ", // ⟂ 
        "\u{027C5}" => "\\Lbag ", // ⟅ 
        "\u{027C6}" => "\\Rbag ", // ⟆ 
        "\u{027D0}" => "\\Diamonddot ", // ⟐ 
        "\u{027DC}" => "\\multimapinv ", // ⟜ 
        "\u{027E6}" => "\\llbracket ", // ⟦ 
        "\u{027E7}" => "\\rrbracket ", // ⟧ 
        "\u{027E8}" => "\\langle ", // ⟨ 
        "\u{027E9}" => "\\rangle ", // ⟩ 
        "\u{027EA}" => "\\lang ", // ⟪ 
        "\u{027EB}" => "\\rang ", // ⟫ 
        "\u{027EE}" => "\\lgroup ", // ⟮ 
        "\u{027EF}" => "\\rgroup ", // ⟯ 
        "\u{027F5}" => "\\longleftarrow ", // ⟵ 
        "\u{027F6}" => "\\longrightarrow ", // ⟶ 
        "\u{027F7}" => "\\longleftrightarrow ", // ⟷ 
        "\u{027F8}" => "\\Longleftarrow ", // ⟸ 
        "\u{027F9}" => "\\Longrightarrow ", // ⟹ 
        "\u{027FA}" => "\\Longleftrightarrow ", // ⟺ 
        "\u{027FB}" => "\\longmapsfrom ", // ⟻ 
        "\u{027FC}" => "\\longmapsto ", // ⟼ 
        "\u{027FD}" => "\\Longmapsfrom ", // ⟽ 
        "\u{027FE}" => "\\Longmapsto ", // ⟾ 
        "\u{02900}" => "\\psur ", // ⤀ 
        "\u{02906}" => "\\Mapsfrom ", // ⤆ 
        "\u{02907}" => "\\Mapsto ", // ⤇ 
        "\u{02912}" => "\\UpArrowBar ", // ⤒ 
        "\u{02913}" => "\\DownArrowBar ", // ⤓ 
        "\u{02914}" => "\\pinj ", // ⤔ 
        "\u{02915}" => "\\finj ", // ⤕ 
        "\u{02916}" => "\\bij ", // ⤖ 
        "\u{02933}" => "\\leadsto ", // ⤳ 
        "\u{0294A}" => "\\leftrightharpoon ", // ⥊ 
        "\u{0294B}" => "\\rightleftharpoon ", // ⥋ 
        "\u{0294E}" => "\\leftrightharpoonup ", // ⥎ 
        "\u{0294F}" => "\\rightupdownharpoon ", // ⥏ 
        "\u{02950}" => "\\leftrightharpoondown ", // ⥐ 
        "\u{02951}" => "\\leftupdownharpoon ", // ⥑ 
        "\u{02952}" => "\\LeftVectorBar ", // ⥒ 
        "\u{02953}" => "\\RightVectorBar ", // ⥓ 
        "\u{02954}" => "\\RightUpVectorBar ", // ⥔ 
        "\u{02955}" => "\\RightDownVectorBar ", // ⥕ 
        "\u{02956}" => "\\DownLeftVectorBar ", // ⥖ 
        "\u{02957}" => "\\DownRightVectorBar ", // ⥗ 
        "\u{02958}" => "\\LeftUpVectorBar ", // ⥘ 
        "\u{02959}" => "\\LeftDownVectorBar ", // ⥙ 
        "\u{0295A}" => "\\LeftTeeVector ", // ⥚ 
        "\u{0295B}" => "\\RightTeeVector ", // ⥛ 
        "\u{0295C}" => "\\RightUpTeeVector ", // ⥜ 
        "\u{0295D}" => "\\RightDownTeeVector ", // ⥝ 
        "\u{0295E}" => "\\DownLeftTeeVector ", // ⥞ 
        "\u{0295F}" => "\\DownRightTeeVector ", // ⥟ 
        "\u{02960}" => "\\LeftUpTeeVector ", // ⥠ 
        "\u{02961}" => "\\LeftDownTeeVector ", // ⥡ 
        "\u{02962}" => "\\leftleftharpoons ", // ⥢ 
        "\u{02963}" => "\\upupharpoons ", // ⥣ 
        "\u{02964}" => "\\rightrightharpoons ", // ⥤ 
        "\u{02965}" => "\\downdownharpoons ", // ⥥ 
        "\u{0296A}" => "\\leftbarharpoon ", // ⥪ 
        "\u{0296B}" => "\\barleftharpoon ", // ⥫ 
        "\u{0296C}" => "\\rightbarharpoon ", // ⥬ 
        "\u{0296D}" => "\\barrightharpoon ", // ⥭ 
        "\u{0296E}" => "\\updownharpoons ", // ⥮ 
        "\u{0296F}" => "\\downupharpoons ", // ⥯ 
        "\u{0297C}" => "\\strictfi ", // ⥼ 
        "\u{0297D}" => "\\strictif ", // ⥽ 
        "\u{02980}" => "\\VERT ", // ⦀ 
        "\u{02981}" => "\\spot ", // ⦁ 
        "\u{02985}" => "\\Lparen ", // ⦅ 
        "\u{02986}" => "\\Rparen ", // ⦆ 
        "\u{02987}" => "\\limg ", // ⦇ 
        "\u{02988}" => "\\rimg ", // ⦈ 
        "\u{02989}" => "\\lblot ", // ⦉ 
        "\u{0298A}" => "\\rblot ", // ⦊ 
        "\u{029B8}" => "\\circledbslash ", // ⦸ 
        "\u{029C0}" => "\\circledless ", // ⧀ 
        "\u{029C1}" => "\\circledgtr ", // ⧁ 
        "\u{029C4}" => "\\boxslash ", // ⧄ 
        "\u{029C5}" => "\\boxbslash ", // ⧅ 
        "\u{029C6}" => "\\boxast ", // ⧆ 
        "\u{029C7}" => "\\boxcircle ", // ⧇ 
        "\u{029C8}" => "\\boxbox ", // ⧈ 
        "\u{029CF}" => "\\LeftTriangleBar ", // ⧏ 
        "\u{029D0}" => "\\RightTriangleBar ", // ⧐ 
        "\u{029DF}" => "\\multimapboth ", // ⧟ 
        "\u{029EB}" => "\\blacklozenge ", // ⧫ 
        "\u{029F5}" => "\\setminus ", // ⧵ 
        "\u{029F9}" => "\\zhide ", // ⧹ 
        "\u{02A00}" => "\\bigodot ", // ⨀ 
        "\u{02A01}" => "\\bigoplus ", // ⨁ 
        "\u{02A02}" => "\\bigotimes ", // ⨂ 
        "\u{02A04}" => "\\biguplus ", // ⨄ 
        "\u{02A05}" => "\\bigsqcap ", // ⨅ 
        "\u{02A06}" => "\\bigsqcup ", // ⨆ 
        "\u{02A09}" => "\\varprod ", // ⨉ 
        "\u{02A0C}" => "\\iiiint ", // ⨌ 
        "\u{02A0F}" => "\\fint ", // ⨏ 
        "\u{02A16}" => "\\sqint ", // ⨖ 
        "\u{02A1D}" => "\\Join ", // ⨝ 
        "\u{02A1F}" => "\\zcmp ", // ⨟ 
        "\u{02A20}" => "\\zpipe ", // ⨠ 
        "\u{02A21}" => "\\zproject ", // ⨡ 
        "\u{02A3E}" => "\\fcmp ", // ⨾ 
        "\u{02A3F}" => "\\amalg ", // ⨿ 
        "\u{02A5E}" => "\\doublebarwedge ", // ⩞ 
        "\u{02A64}" => "\\dsub ", // ⩤ 
        "\u{02A65}" => "\\rsub ", // ⩥ 
        "\u{02A74}" => "\\Coloneqq ", // ⩴ 
        "\u{02A75}" => "\\Equal ", // ⩵ 
        "\u{02A76}" => "\\Same ", // ⩶ 
        "\u{02A7D}" => "\\leqslant ", // ⩽ 
        "\u{02A7E}" => "\\geqslant ", // ⩾ 
        "\u{02A85}" => "\\lessapprox ", // ⪅ 
        "\u{02A86}" => "\\gtrapprox ", // ⪆ 
        "\u{02A87}" => "\\lneq ", // ⪇ 
        "\u{02A88}" => "\\gneq ", // ⪈ 
        "\u{02A89}" => "\\lnapprox ", // ⪉ 
        "\u{02A8A}" => "\\gnapprox ", // ⪊ 
        "\u{02A8B}" => "\\lesseqqgtr ", // ⪋ 
        "\u{02A8C}" => "\\gtreqqless ", // ⪌ 
        "\u{02A95}" => "\\eqslantless ", // ⪕ 
        "\u{02A96}" => "\\eqslantgtr ", // ⪖ 
        "\u{02AA1}" => "\\NestedLessLess ", // ⪡ 
        "\u{02AA2}" => "\\NestedGreaterGreater ", // ⪢ 
        "\u{02AA6}" => "\\leftslice ", // ⪦ 
        "\u{02AA7}" => "\\rightslice ", // ⪧ 
        "\u{02AAF}" => "\\preceq ", // ⪯ 
        "\u{02AB0}" => "\\succeq ", // ⪰ 
        "\u{02AB3}" => "\\preceqq ", // ⪳ 
        "\u{02AB4}" => "\\succeqq ", // ⪴ 
        "\u{02AB7}" => "\\precapprox ", // ⪷ 
        "\u{02AB8}" => "\\succapprox ", // ⪸ 
        "\u{02AB9}" => "\\precnapprox ", // ⪹ 
        "\u{02ABA}" => "\\succnapprox ", // ⪺ 
        "\u{02ABB}" => "\\llcurly ", // ⪻ 
        "\u{02ABC}" => "\\ggcurly ", // ⪼ 
        "\u{02AC5}" => "\\subseteqq ", // ⫅ 
        "\u{02AC6}" => "\\supseteqq ", // ⫆ 
        "\u{02ACB}" => "\\subsetneqq ", // ⫋ 
        "\u{02ACC}" => "\\supsetneqq ", // ⫌ 
        "\u{02AEA}" => "\\Top ", // ⫪ 
        "\u{02AEB}" => "\\Bot ", // ⫫ 
        "\u{02AF4}" => "\\interleave ", // ⫴ 
        "\u{02AFC}" => "\\biginterleave ", // ⫼ 
        "\u{02AFD}" => "\\sslash ", // ⫽ 
        "\u{02AFE}" => "\\talloblong ", // ⫾ 
        "\u{02B1B}" => "\\blacksquare ", // ⬛ 
        "\u{02B1C}" => "\\square ", // ⬜ 
        "\u{1D400}" => "\\mathbf{A} ", // 𝐀 
        "\u{1D401}" => "\\mathbf{B} ", // 𝐁 
        "\u{1D402}" => "\\mathbf{C} ", // 𝐂 
        "\u{1D403}" => "\\mathbf{D} ", // 𝐃 
        "\u{1D404}" => "\\mathbf{E} ", // 𝐄 
        "\u{1D405}" => "\\mathbf{F} ", // 𝐅 
        "\u{1D406}" => "\\mathbf{G} ", // 𝐆 
        "\u{1D407}" => "\\mathbf{H} ", // 𝐇 
        "\u{1D408}" => "\\mathbf{I} ", // 𝐈 
        "\u{1D409}" => "\\mathbf{J} ", // 𝐉 
        "\u{1D40A}" => "\\mathbf{K} ", // 𝐊 
        "\u{1D40B}" => "\\mathbf{L} ", // 𝐋 
        "\u{1D40C}" => "\\mathbf{M} ", // 𝐌 
        "\u{1D40D}" => "\\mathbf{N} ", // 𝐍 
        "\u{1D40E}" => "\\mathbf{O} ", // 𝐎 
        "\u{1D40F}" => "\\mathbf{P} ", // 𝐏 
        "\u{1D410}" => "\\mathbf{Q} ", // 𝐐 
        "\u{1D411}" => "\\mathbf{R} ", // 𝐑 
        "\u{1D412}" => "\\mathbf{S} ", // 𝐒 
        "\u{1D413}" => "\\mathbf{T} ", // 𝐓 
        "\u{1D414}" => "\\mathbf{U} ", // 𝐔 
        "\u{1D415}" => "\\mathbf{V} ", // 𝐕 
        "\u{1D416}" => "\\mathbf{W} ", // 𝐖 
        "\u{1D417}" => "\\mathbf{X} ", // 𝐗 
        "\u{1D418}" => "\\mathbf{Y} ", // 𝐘 
        "\u{1D419}" => "\\mathbf{Z} ", // 𝐙 
        "\u{1D41A}" => "\\mathbf{a} ", // 𝐚 
        "\u{1D41B}" => "\\mathbf{b} ", // 𝐛 
        "\u{1D41C}" => "\\mathbf{c} ", // 𝐜 
        "\u{1D41D}" => "\\mathbf{d} ", // 𝐝 
        "\u{1D41E}" => "\\mathbf{e} ", // 𝐞 
        "\u{1D41F}" => "\\mathbf{f} ", // 𝐟 
        "\u{1D420}" => "\\mathbf{g} ", // 𝐠 
        "\u{1D421}" => "\\mathbf{h} ", // 𝐡 
        "\u{1D422}" => "\\mathbf{i} ", // 𝐢 
        "\u{1D423}" => "\\mathbf{j} ", // 𝐣 
        "\u{1D424}" => "\\mathbf{k} ", // 𝐤 
        "\u{1D425}" => "\\mathbf{l} ", // 𝐥 
        "\u{1D426}" => "\\mathbf{m} ", // 𝐦 
        "\u{1D427}" => "\\mathbf{n} ", // 𝐧 
        "\u{1D428}" => "\\mathbf{o} ", // 𝐨 
        "\u{1D429}" => "\\mathbf{p} ", // 𝐩 
        "\u{1D42A}" => "\\mathbf{q} ", // 𝐪 
        "\u{1D42B}" => "\\mathbf{r} ", // 𝐫 
        "\u{1D42C}" => "\\mathbf{s} ", // 𝐬 
        "\u{1D42D}" => "\\mathbf{t} ", // 𝐭 
        "\u{1D42E}" => "\\mathbf{u} ", // 𝐮 
        "\u{1D42F}" => "\\mathbf{v} ", // 𝐯 
        "\u{1D430}" => "\\mathbf{w} ", // 𝐰 
        "\u{1D431}" => "\\mathbf{x} ", // 𝐱 
        "\u{1D432}" => "\\mathbf{y} ", // 𝐲 
        "\u{1D433}" => "\\mathbf{z} ", // 𝐳 
        "\u{1D434}" => "A", // 𝐴 
        "\u{1D435}" => "B", // 𝐵 
        "\u{1D436}" => "C", // 𝐶 
        "\u{1D437}" => "D", // 𝐷 
        "\u{1D438}" => "E", // 𝐸 
        "\u{1D439}" => "F", // 𝐹 
        "\u{1D43A}" => "G", // 𝐺 
        "\u{1D43B}" => "H", // 𝐻 
        "\u{1D43C}" => "I", // 𝐼 
        "\u{1D43D}" => "J", // 𝐽 
        "\u{1D43E}" => "K", // 𝐾 
        "\u{1D43F}" => "L", // 𝐿 
        "\u{1D440}" => "M", // 𝑀 
        "\u{1D441}" => "N", // 𝑁 
        "\u{1D442}" => "O", // 𝑂 
        "\u{1D443}" => "P", // 𝑃 
        "\u{1D444}" => "Q", // 𝑄 
        "\u{1D445}" => "R", // 𝑅 
        "\u{1D446}" => "S", // 𝑆 
        "\u{1D447}" => "T", // 𝑇 
        "\u{1D448}" => "U", // 𝑈 
        "\u{1D449}" => "V", // 𝑉 
        "\u{1D44A}" => "W", // 𝑊 
        "\u{1D44B}" => "X", // 𝑋 
        "\u{1D44C}" => "Y", // 𝑌 
        "\u{1D44D}" => "Z", // 𝑍 
        "\u{1D44E}" => "a", // 𝑎 
        "\u{1D44F}" => "b", // 𝑏 
        "\u{1D450}" => "c", // 𝑐 
        "\u{1D451}" => "d", // 𝑑 
        "\u{1D452}" => "e", // 𝑒 
        "\u{1D453}" => "f", // 𝑓 
        "\u{1D454}" => "g", // 𝑔 
        "\u{1D456}" => "i", // 𝑖 
        "\u{1D457}" => "j", // 𝑗 
        "\u{1D458}" => "k", // 𝑘 
        "\u{1D459}" => "l", // 𝑙 
        "\u{1D45A}" => "m", // 𝑚 
        "\u{1D45B}" => "n", // 𝑛 
        "\u{1D45C}" => "o", // 𝑜 
        "\u{1D45D}" => "p", // 𝑝 
        "\u{1D45E}" => "q", // 𝑞 
        "\u{1D45F}" => "r", // 𝑟 
        "\u{1D460}" => "s", // 𝑠 
        "\u{1D461}" => "t", // 𝑡 
        "\u{1D462}" => "u", // 𝑢 
        "\u{1D463}" => "v", // 𝑣 
        "\u{1D464}" => "w", // 𝑤 
        "\u{1D465}" => "x", // 𝑥 
        "\u{1D466}" => "y", // 𝑦 
        "\u{1D467}" => "z", // 𝑧 
        "\u{1D468}" => "\\mathbfit{A} ", // 𝑨 
        "\u{1D469}" => "\\mathbfit{B} ", // 𝑩 
        "\u{1D46A}" => "\\mathbfit{C} ", // 𝑪 
        "\u{1D46B}" => "\\mathbfit{D} ", // 𝑫 
        "\u{1D46C}" => "\\mathbfit{E} ", // 𝑬 
        "\u{1D46D}" => "\\mathbfit{F} ", // 𝑭 
        "\u{1D46E}" => "\\mathbfit{G} ", // 𝑮 
        "\u{1D46F}" => "\\mathbfit{H} ", // 𝑯 
        "\u{1D470}" => "\\mathbfit{I} ", // 𝑰 
        "\u{1D471}" => "\\mathbfit{J} ", // 𝑱 
        "\u{1D472}" => "\\mathbfit{K} ", // 𝑲 
        "\u{1D473}" => "\\mathbfit{L} ", // 𝑳 
        "\u{1D474}" => "\\mathbfit{M} ", // 𝑴 
        "\u{1D475}" => "\\mathbfit{N} ", // 𝑵 
        "\u{1D476}" => "\\mathbfit{O} ", // 𝑶 
        "\u{1D477}" => "\\mathbfit{P} ", // 𝑷 
        "\u{1D478}" => "\\mathbfit{Q} ", // 𝑸 
        "\u{1D479}" => "\\mathbfit{R} ", // 𝑹 
        "\u{1D47A}" => "\\mathbfit{S} ", // 𝑺 
        "\u{1D47B}" => "\\mathbfit{T} ", // 𝑻 
        "\u{1D47C}" => "\\mathbfit{U} ", // 𝑼 
        "\u{1D47D}" => "\\mathbfit{V} ", // 𝑽 
        "\u{1D47E}" => "\\mathbfit{W} ", // 𝑾 
        "\u{1D47F}" => "\\mathbfit{X} ", // 𝑿 
        "\u{1D480}" => "\\mathbfit{Y} ", // 𝒀 
        "\u{1D481}" => "\\mathbfit{Z} ", // 𝒁 
        "\u{1D482}" => "\\mathbfit{a} ", // 𝒂 
        "\u{1D483}" => "\\mathbfit{b} ", // 𝒃 
        "\u{1D484}" => "\\mathbfit{c} ", // 𝒄 
        "\u{1D485}" => "\\mathbfit{d} ", // 𝒅 
        "\u{1D486}" => "\\mathbfit{e} ", // 𝒆 
        "\u{1D487}" => "\\mathbfit{f} ", // 𝒇 
        "\u{1D488}" => "\\mathbfit{g} ", // 𝒈 
        "\u{1D489}" => "\\mathbfit{h} ", // 𝒉 
        "\u{1D48A}" => "\\mathbfit{i} ", // 𝒊 
        "\u{1D48B}" => "\\mathbfit{j} ", // 𝒋 
        "\u{1D48C}" => "\\mathbfit{k} ", // 𝒌 
        "\u{1D48D}" => "\\mathbfit{l} ", // 𝒍 
        "\u{1D48E}" => "\\mathbfit{m} ", // 𝒎 
        "\u{1D48F}" => "\\mathbfit{n} ", // 𝒏 
        "\u{1D490}" => "\\mathbfit{o} ", // 𝒐 
        "\u{1D491}" => "\\mathbfit{p} ", // 𝒑 
        "\u{1D492}" => "\\mathbfit{q} ", // 𝒒 
        "\u{1D493}" => "\\mathbfit{r} ", // 𝒓 
        "\u{1D494}" => "\\mathbfit{s} ", // 𝒔 
        "\u{1D495}" => "\\mathbfit{t} ", // 𝒕 
        "\u{1D496}" => "\\mathbfit{u} ", // 𝒖 
        "\u{1D497}" => "\\mathbfit{v} ", // 𝒗 
        "\u{1D498}" => "\\mathbfit{w} ", // 𝒘 
        "\u{1D499}" => "\\mathbfit{x} ", // 𝒙 
        "\u{1D49A}" => "\\mathbfit{y} ", // 𝒚 
        "\u{1D49B}" => "\\mathbfit{z} ", // 𝒛 
        "\u{1D49C}" => "\\mathcal{A} ", // 𝒜 
        "\u{1D49E}" => "\\mathcal{C} ", // 𝒞 
        "\u{1D49F}" => "\\mathcal{D} ", // 𝒟 
        "\u{1D4A2}" => "\\mathcal{G} ", // 𝒢 
        "\u{1D4A5}" => "\\mathcal{J} ", // 𝒥 
        "\u{1D4A6}" => "\\mathcal{K} ", // 𝒦 
        "\u{1D4A9}" => "\\mathcal{N} ", // 𝒩 
        "\u{1D4AA}" => "\\mathcal{O} ", // 𝒪 
        "\u{1D4AB}" => "\\mathcal{P} ", // 𝒫 
        "\u{1D4AC}" => "\\mathcal{Q} ", // 𝒬 
        "\u{1D4AE}" => "\\mathcal{S} ", // 𝒮 
        "\u{1D4AF}" => "\\mathcal{T} ", // 𝒯 
        "\u{1D4B0}" => "\\mathcal{U} ", // 𝒰 
        "\u{1D4B1}" => "\\mathcal{V} ", // 𝒱 
        "\u{1D4B2}" => "\\mathcal{W} ", // 𝒲 
        "\u{1D4B3}" => "\\mathcal{X} ", // 𝒳 
        "\u{1D4B4}" => "\\mathcal{Y} ", // 𝒴 
        "\u{1D4B5}" => "\\mathcal{Z} ", // 𝒵 
        "\u{1D4B6}" => "\\mathcal{a} ", // 𝒶 
        "\u{1D4B7}" => "\\mathcal{b} ", // 𝒷 
        "\u{1D4B8}" => "\\mathcal{c} ", // 𝒸 
        "\u{1D4B9}" => "\\mathcal{d} ", // 𝒹 
        "\u{1D4BB}" => "\\mathcal{f} ", // 𝒻 
        "\u{1D4BD}" => "\\mathcal{h} ", // 𝒽 
        "\u{1D4BE}" => "\\mathcal{i} ", // 𝒾 
        "\u{1D4BF}" => "\\mathcal{j} ", // 𝒿 
        "\u{1D4C0}" => "\\mathcal{k} ", // 𝓀 
        "\u{1D4C1}" => "\\mathcal{l} ", // 𝓁 
        "\u{1D4C2}" => "\\mathcal{m} ", // 𝓂 
        "\u{1D4C3}" => "\\mathcal{n} ", // 𝓃 
        "\u{1D4C5}" => "\\mathcal{p} ", // 𝓅 
        "\u{1D4C6}" => "\\mathcal{q} ", // 𝓆 
        "\u{1D4C7}" => "\\mathcal{r} ", // 𝓇 
        "\u{1D4C8}" => "\\mathcal{s} ", // 𝓈 
        "\u{1D4C9}" => "\\mathcal{t} ", // 𝓉 
        "\u{1D4CA}" => "\\mathcal{u} ", // 𝓊 
        "\u{1D4CB}" => "\\mathcal{v} ", // 𝓋 
        "\u{1D4CC}" => "\\mathcal{w} ", // 𝓌 
        "\u{1D4CD}" => "\\mathcal{x} ", // 𝓍 
        "\u{1D4CE}" => "\\mathcal{y} ", // 𝓎 
        "\u{1D4CF}" => "\\mathcal{z} ", // 𝓏 
        "\u{1D504}" => "\\mathfrak{A} ", // 𝔄 
        "\u{1D505}" => "\\mathfrak{B} ", // 𝔅 
        "\u{1D507}" => "\\mathfrak{D} ", // 𝔇 
        "\u{1D508}" => "\\mathfrak{E} ", // 𝔈 
        "\u{1D509}" => "\\mathfrak{F} ", // 𝔉 
        "\u{1D50A}" => "\\mathfrak{G} ", // 𝔊 
        "\u{1D50D}" => "\\mathfrak{J} ", // 𝔍 
        "\u{1D50E}" => "\\mathfrak{K} ", // 𝔎 
        "\u{1D50F}" => "\\mathfrak{L} ", // 𝔏 
        "\u{1D510}" => "\\mathfrak{M} ", // 𝔐 
        "\u{1D511}" => "\\mathfrak{N} ", // 𝔑 
        "\u{1D512}" => "\\mathfrak{O} ", // 𝔒 
        "\u{1D513}" => "\\mathfrak{P} ", // 𝔓 
        "\u{1D514}" => "\\mathfrak{Q} ", // 𝔔 
        "\u{1D516}" => "\\mathfrak{S} ", // 𝔖 
        "\u{1D517}" => "\\mathfrak{T} ", // 𝔗 
        "\u{1D518}" => "\\mathfrak{U} ", // 𝔘 
        "\u{1D519}" => "\\mathfrak{V} ", // 𝔙 
        "\u{1D51A}" => "\\mathfrak{W} ", // 𝔚 
        "\u{1D51B}" => "\\mathfrak{X} ", // 𝔛 
        "\u{1D51C}" => "\\mathfrak{Y} ", // 𝔜 
        "\u{1D51E}" => "\\mathfrak{a} ", // 𝔞 
        "\u{1D51F}" => "\\mathfrak{b} ", // 𝔟 
        "\u{1D520}" => "\\mathfrak{c} ", // 𝔠 
        "\u{1D521}" => "\\mathfrak{d} ", // 𝔡 
        "\u{1D522}" => "\\mathfrak{e} ", // 𝔢 
        "\u{1D523}" => "\\mathfrak{f} ", // 𝔣 
        "\u{1D524}" => "\\mathfrak{g} ", // 𝔤 
        "\u{1D525}" => "\\mathfrak{h} ", // 𝔥 
        "\u{1D526}" => "\\mathfrak{i} ", // 𝔦 
        "\u{1D527}" => "\\mathfrak{j} ", // 𝔧 
        "\u{1D528}" => "\\mathfrak{k} ", // 𝔨 
        "\u{1D529}" => "\\mathfrak{l} ", // 𝔩 
        "\u{1D52A}" => "\\mathfrak{m} ", // 𝔪 
        "\u{1D52B}" => "\\mathfrak{n} ", // 𝔫 
        "\u{1D52C}" => "\\mathfrak{o} ", // 𝔬 
        "\u{1D52D}" => "\\mathfrak{p} ", // 𝔭 
        "\u{1D52E}" => "\\mathfrak{q} ", // 𝔮 
        "\u{1D52F}" => "\\mathfrak{r} ", // 𝔯 
        "\u{1D530}" => "\\mathfrak{s} ", // 𝔰 
        "\u{1D531}" => "\\mathfrak{t} ", // 𝔱 
        "\u{1D532}" => "\\mathfrak{u} ", // 𝔲 
        "\u{1D533}" => "\\mathfrak{v} ", // 𝔳 
        "\u{1D534}" => "\\mathfrak{w} ", // 𝔴 
        "\u{1D535}" => "\\mathfrak{x} ", // 𝔵 
        "\u{1D536}" => "\\mathfrak{y} ", // 𝔶 
        "\u{1D537}" => "\\mathfrak{z} ", // 𝔷 
        "\u{1D538}" => "\\mathbb{A} ", // 𝔸 
        "\u{1D539}" => "\\mathbb{B} ", // 𝔹 
        "\u{1D53B}" => "\\mathbb{D} ", // 𝔻 
        "\u{1D53C}" => "\\mathbb{E} ", // 𝔼 
        "\u{1D53D}" => "\\mathbb{F} ", // 𝔽 
        "\u{1D53E}" => "\\mathbb{G} ", // 𝔾 
        "\u{1D540}" => "\\mathbb{I} ", // 𝕀 
        "\u{1D541}" => "\\mathbb{J} ", // 𝕁 
        "\u{1D542}" => "\\mathbb{K} ", // 𝕂 
        "\u{1D543}" => "\\mathbb{L} ", // 𝕃 
        "\u{1D544}" => "\\mathbb{M} ", // 𝕄 
        "\u{1D546}" => "\\mathbb{O} ", // 𝕆 
        "\u{1D54A}" => "\\mathbb{S} ", // 𝕊 
        "\u{1D54B}" => "\\mathbb{T} ", // 𝕋 
        "\u{1D54C}" => "\\mathbb{U} ", // 𝕌 
        "\u{1D54D}" => "\\mathbb{V} ", // 𝕍 
        "\u{1D54E}" => "\\mathbb{W} ", // 𝕎 
        "\u{1D54F}" => "\\mathbb{X} ", // 𝕏 
        "\u{1D550}" => "\\mathbb{Y} ", // 𝕐 
        "\u{1D552}" => "\\mathbb{a} ", // 𝕒 
        "\u{1D553}" => "\\mathbb{b} ", // 𝕓 
        "\u{1D554}" => "\\mathbb{c} ", // 𝕔 
        "\u{1D555}" => "\\mathbb{d} ", // 𝕕 
        "\u{1D556}" => "\\mathbb{e} ", // 𝕖 
        "\u{1D557}" => "\\mathbb{f} ", // 𝕗 
        "\u{1D558}" => "\\mathbb{g} ", // 𝕘 
        "\u{1D559}" => "\\mathbb{h} ", // 𝕙 
        "\u{1D55A}" => "\\mathbb{i} ", // 𝕚 
        "\u{1D55B}" => "\\mathbb{j} ", // 𝕛 
        "\u{1D55C}" => "\\mathbb{k} ", // 𝕜 
        "\u{1D55D}" => "\\mathbb{l} ", // 𝕝 
        "\u{1D55E}" => "\\mathbb{m} ", // 𝕞 
        "\u{1D55F}" => "\\mathbb{n} ", // 𝕟 
        "\u{1D560}" => "\\mathbb{o} ", // 𝕠 
        "\u{1D561}" => "\\mathbb{p} ", // 𝕡 
        "\u{1D562}" => "\\mathbb{q} ", // 𝕢 
        "\u{1D563}" => "\\mathbb{r} ", // 𝕣 
        "\u{1D564}" => "\\mathbb{s} ", // 𝕤 
        "\u{1D565}" => "\\mathbb{t} ", // 𝕥 
        "\u{1D566}" => "\\mathbb{u} ", // 𝕦 
        "\u{1D567}" => "\\mathbb{v} ", // 𝕧 
        "\u{1D568}" => "\\mathbb{w} ", // 𝕨 
        "\u{1D569}" => "\\mathbb{x} ", // 𝕩 
        "\u{1D56A}" => "\\mathbb{y} ", // 𝕪 
        "\u{1D56B}" => "\\mathbb{z} ", // 𝕫 
        "\u{1D5A0}" => "\\mathsf{A} ", // 𝖠 
        "\u{1D5A1}" => "\\mathsf{B} ", // 𝖡 
        "\u{1D5A2}" => "\\mathsf{C} ", // 𝖢 
        "\u{1D5A3}" => "\\mathsf{D} ", // 𝖣 
        "\u{1D5A4}" => "\\mathsf{E} ", // 𝖤 
        "\u{1D5A5}" => "\\mathsf{F} ", // 𝖥 
        "\u{1D5A6}" => "\\mathsf{G} ", // 𝖦 
        "\u{1D5A7}" => "\\mathsf{H} ", // 𝖧 
        "\u{1D5A8}" => "\\mathsf{I} ", // 𝖨 
        "\u{1D5A9}" => "\\mathsf{J} ", // 𝖩 
        "\u{1D5AA}" => "\\mathsf{K} ", // 𝖪 
        "\u{1D5AB}" => "\\mathsf{L} ", // 𝖫 
        "\u{1D5AC}" => "\\mathsf{M} ", // 𝖬 
        "\u{1D5AD}" => "\\mathsf{N} ", // 𝖭 
        "\u{1D5AE}" => "\\mathsf{O} ", // 𝖮 
        "\u{1D5AF}" => "\\mathsf{P} ", // 𝖯 
        "\u{1D5B0}" => "\\mathsf{Q} ", // 𝖰 
        "\u{1D5B1}" => "\\mathsf{R} ", // 𝖱 
        "\u{1D5B2}" => "\\mathsf{S} ", // 𝖲 
        "\u{1D5B3}" => "\\mathsf{T} ", // 𝖳 
        "\u{1D5B4}" => "\\mathsf{U} ", // 𝖴 
        "\u{1D5B5}" => "\\mathsf{V} ", // 𝖵 
        "\u{1D5B6}" => "\\mathsf{W} ", // 𝖶 
        "\u{1D5B7}" => "\\mathsf{X} ", // 𝖷 
        "\u{1D5B8}" => "\\mathsf{Y} ", // 𝖸 
        "\u{1D5B9}" => "\\mathsf{Z} ", // 𝖹 
        "\u{1D5BA}" => "\\mathsf{a} ", // 𝖺 
        "\u{1D5BB}" => "\\mathsf{b} ", // 𝖻 
        "\u{1D5BC}" => "\\mathsf{c} ", // 𝖼 
        "\u{1D5BD}" => "\\mathsf{d} ", // 𝖽 
        "\u{1D5BE}" => "\\mathsf{e} ", // 𝖾 
        "\u{1D5BF}" => "\\mathsf{f} ", // 𝖿 
        "\u{1D5C0}" => "\\mathsf{g} ", // 𝗀 
        "\u{1D5C1}" => "\\mathsf{h} ", // 𝗁 
        "\u{1D5C2}" => "\\mathsf{i} ", // 𝗂 
        "\u{1D5C3}" => "\\mathsf{j} ", // 𝗃 
        "\u{1D5C4}" => "\\mathsf{k} ", // 𝗄 
        "\u{1D5C5}" => "\\mathsf{l} ", // 𝗅 
        "\u{1D5C6}" => "\\mathsf{m} ", // 𝗆 
        "\u{1D5C7}" => "\\mathsf{n} ", // 𝗇 
        "\u{1D5C8}" => "\\mathsf{o} ", // 𝗈 
        "\u{1D5C9}" => "\\mathsf{p} ", // 𝗉 
        "\u{1D5CA}" => "\\mathsf{q} ", // 𝗊 
        "\u{1D5CB}" => "\\mathsf{r} ", // 𝗋 
        "\u{1D5CC}" => "\\mathsf{s} ", // 𝗌 
        "\u{1D5CD}" => "\\mathsf{t} ", // 𝗍 
        "\u{1D5CE}" => "\\mathsf{u} ", // 𝗎 
        "\u{1D5CF}" => "\\mathsf{v} ", // 𝗏 
        "\u{1D5D0}" => "\\mathsf{w} ", // 𝗐 
        "\u{1D5D1}" => "\\mathsf{x} ", // 𝗑 
        "\u{1D5D2}" => "\\mathsf{y} ", // 𝗒 
        "\u{1D5D3}" => "\\mathsf{z} ", // 𝗓 
        "\u{1D5D4}" => "\\mathsfbf{A} ", // 𝗔 
        "\u{1D5D5}" => "\\mathsfbf{B} ", // 𝗕 
        "\u{1D5D6}" => "\\mathsfbf{C} ", // 𝗖 
        "\u{1D5D7}" => "\\mathsfbf{D} ", // 𝗗 
        "\u{1D5D8}" => "\\mathsfbf{E} ", // 𝗘 
        "\u{1D5D9}" => "\\mathsfbf{F} ", // 𝗙 
        "\u{1D5DA}" => "\\mathsfbf{G} ", // 𝗚 
        "\u{1D5DB}" => "\\mathsfbf{H} ", // 𝗛 
        "\u{1D5DC}" => "\\mathsfbf{I} ", // 𝗜 
        "\u{1D5DD}" => "\\mathsfbf{J} ", // 𝗝 
        "\u{1D5DE}" => "\\mathsfbf{K} ", // 𝗞 
        "\u{1D5DF}" => "\\mathsfbf{L} ", // 𝗟 
        "\u{1D5E0}" => "\\mathsfbf{M} ", // 𝗠 
        "\u{1D5E1}" => "\\mathsfbf{N} ", // 𝗡 
        "\u{1D5E2}" => "\\mathsfbf{O} ", // 𝗢 
        "\u{1D5E3}" => "\\mathsfbf{P} ", // 𝗣 
        "\u{1D5E4}" => "\\mathsfbf{Q} ", // 𝗤 
        "\u{1D5E5}" => "\\mathsfbf{R} ", // 𝗥 
        "\u{1D5E6}" => "\\mathsfbf{S} ", // 𝗦 
        "\u{1D5E7}" => "\\mathsfbf{T} ", // 𝗧 
        "\u{1D5E8}" => "\\mathsfbf{U} ", // 𝗨 
        "\u{1D5E9}" => "\\mathsfbf{V} ", // 𝗩 
        "\u{1D5EA}" => "\\mathsfbf{W} ", // 𝗪 
        "\u{1D5EB}" => "\\mathsfbf{X} ", // 𝗫 
        "\u{1D5EC}" => "\\mathsfbf{Y} ", // 𝗬 
        "\u{1D5ED}" => "\\mathsfbf{Z} ", // 𝗭 
        "\u{1D5EE}" => "\\mathsfbf{a} ", // 𝗮 
        "\u{1D5EF}" => "\\mathsfbf{b} ", // 𝗯 
        "\u{1D5F0}" => "\\mathsfbf{c} ", // 𝗰 
        "\u{1D5F1}" => "\\mathsfbf{d} ", // 𝗱 
        "\u{1D5F2}" => "\\mathsfbf{e} ", // 𝗲 
        "\u{1D5F3}" => "\\mathsfbf{f} ", // 𝗳 
        "\u{1D5F4}" => "\\mathsfbf{g} ", // 𝗴 
        "\u{1D5F5}" => "\\mathsfbf{h} ", // 𝗵 
        "\u{1D5F6}" => "\\mathsfbf{i} ", // 𝗶 
        "\u{1D5F7}" => "\\mathsfbf{j} ", // 𝗷 
        "\u{1D5F8}" => "\\mathsfbf{k} ", // 𝗸 
        "\u{1D5F9}" => "\\mathsfbf{l} ", // 𝗹 
        "\u{1D5FA}" => "\\mathsfbf{m} ", // 𝗺 
        "\u{1D5FB}" => "\\mathsfbf{n} ", // 𝗻 
        "\u{1D5FC}" => "\\mathsfbf{o} ", // 𝗼 
        "\u{1D5FD}" => "\\mathsfbf{p} ", // 𝗽 
        "\u{1D5FE}" => "\\mathsfbf{q} ", // 𝗾 
        "\u{1D5FF}" => "\\mathsfbf{r} ", // 𝗿 
        "\u{1D600}" => "\\mathsfbf{s} ", // 𝘀 
        "\u{1D601}" => "\\mathsfbf{t} ", // 𝘁 
        "\u{1D602}" => "\\mathsfbf{u} ", // 𝘂 
        "\u{1D603}" => "\\mathsfbf{v} ", // 𝘃 
        "\u{1D604}" => "\\mathsfbf{w} ", // 𝘄 
        "\u{1D605}" => "\\mathsfbf{x} ", // 𝘅 
        "\u{1D606}" => "\\mathsfbf{y} ", // 𝘆 
        "\u{1D607}" => "\\mathsfbf{z} ", // 𝘇 
        "\u{1D608}" => "\\mathsfit{A} ", // 𝘈 
        "\u{1D609}" => "\\mathsfit{B} ", // 𝘉 
        "\u{1D60A}" => "\\mathsfit{C} ", // 𝘊 
        "\u{1D60B}" => "\\mathsfit{D} ", // 𝘋 
        "\u{1D60C}" => "\\mathsfit{E} ", // 𝘌 
        "\u{1D60D}" => "\\mathsfit{F} ", // 𝘍 
        "\u{1D60E}" => "\\mathsfit{G} ", // 𝘎 
        "\u{1D60F}" => "\\mathsfit{H} ", // 𝘏 
        "\u{1D610}" => "\\mathsfit{I} ", // 𝘐 
        "\u{1D611}" => "\\mathsfit{J} ", // 𝘑 
        "\u{1D612}" => "\\mathsfit{K} ", // 𝘒 
        "\u{1D613}" => "\\mathsfit{L} ", // 𝘓 
        "\u{1D614}" => "\\mathsfit{M} ", // 𝘔 
        "\u{1D615}" => "\\mathsfit{N} ", // 𝘕 
        "\u{1D616}" => "\\mathsfit{O} ", // 𝘖 
        "\u{1D617}" => "\\mathsfit{P} ", // 𝘗 
        "\u{1D618}" => "\\mathsfit{Q} ", // 𝘘 
        "\u{1D619}" => "\\mathsfit{R} ", // 𝘙 
        "\u{1D61A}" => "\\mathsfit{S} ", // 𝘚 
        "\u{1D61B}" => "\\mathsfit{T} ", // 𝘛 
        "\u{1D61C}" => "\\mathsfit{U} ", // 𝘜 
        "\u{1D61D}" => "\\mathsfit{V} ", // 𝘝 
        "\u{1D61E}" => "\\mathsfit{W} ", // 𝘞 
        "\u{1D61F}" => "\\mathsfit{X} ", // 𝘟 
        "\u{1D620}" => "\\mathsfit{Y} ", // 𝘠 
        "\u{1D621}" => "\\mathsfit{Z} ", // 𝘡 
        "\u{1D622}" => "\\mathsfit{a} ", // 𝘢 
        "\u{1D623}" => "\\mathsfit{b} ", // 𝘣 
        "\u{1D624}" => "\\mathsfit{c} ", // 𝘤 
        "\u{1D625}" => "\\mathsfit{d} ", // 𝘥 
        "\u{1D626}" => "\\mathsfit{e} ", // 𝘦 
        "\u{1D627}" => "\\mathsfit{f} ", // 𝘧 
        "\u{1D628}" => "\\mathsfit{g} ", // 𝘨 
        "\u{1D629}" => "\\mathsfit{h} ", // 𝘩 
        "\u{1D62A}" => "\\mathsfit{i} ", // 𝘪 
        "\u{1D62B}" => "\\mathsfit{j} ", // 𝘫 
        "\u{1D62C}" => "\\mathsfit{k} ", // 𝘬 
        "\u{1D62D}" => "\\mathsfit{l} ", // 𝘭 
        "\u{1D62E}" => "\\mathsfit{m} ", // 𝘮 
        "\u{1D62F}" => "\\mathsfit{n} ", // 𝘯 
        "\u{1D630}" => "\\mathsfit{o} ", // 𝘰 
        "\u{1D631}" => "\\mathsfit{p} ", // 𝘱 
        "\u{1D632}" => "\\mathsfit{q} ", // 𝘲 
        "\u{1D633}" => "\\mathsfit{r} ", // 𝘳 
        "\u{1D634}" => "\\mathsfit{s} ", // 𝘴 
        "\u{1D635}" => "\\mathsfit{t} ", // 𝘵 
        "\u{1D636}" => "\\mathsfit{u} ", // 𝘶 
        "\u{1D637}" => "\\mathsfit{v} ", // 𝘷 
        "\u{1D638}" => "\\mathsfit{w} ", // 𝘸 
        "\u{1D639}" => "\\mathsfit{x} ", // 𝘹 
        "\u{1D63A}" => "\\mathsfit{y} ", // 𝘺 
        "\u{1D63B}" => "\\mathsfit{z} ", // 𝘻 
        "\u{1D63C}" => "\\mathsfbfit{A} ", // 𝘼 
        "\u{1D63D}" => "\\mathsfbfit{B} ", // 𝘽 
        "\u{1D63E}" => "\\mathsfbfit{C} ", // 𝘾 
        "\u{1D63F}" => "\\mathsfbfit{D} ", // 𝘿 
        "\u{1D640}" => "\\mathsfbfit{E} ", // 𝙀 
        "\u{1D641}" => "\\mathsfbfit{F} ", // 𝙁 
        "\u{1D642}" => "\\mathsfbfit{G} ", // 𝙂 
        "\u{1D643}" => "\\mathsfbfit{H} ", // 𝙃 
        "\u{1D644}" => "\\mathsfbfit{I} ", // 𝙄 
        "\u{1D645}" => "\\mathsfbfit{J} ", // 𝙅 
        "\u{1D646}" => "\\mathsfbfit{K} ", // 𝙆 
        "\u{1D647}" => "\\mathsfbfit{L} ", // 𝙇 
        "\u{1D648}" => "\\mathsfbfit{M} ", // 𝙈 
        "\u{1D649}" => "\\mathsfbfit{N} ", // 𝙉 
        "\u{1D64A}" => "\\mathsfbfit{O} ", // 𝙊 
        "\u{1D64B}" => "\\mathsfbfit{P} ", // 𝙋 
        "\u{1D64C}" => "\\mathsfbfit{Q} ", // 𝙌 
        "\u{1D64D}" => "\\mathsfbfit{R} ", // 𝙍 
        "\u{1D64E}" => "\\mathsfbfit{S} ", // 𝙎 
        "\u{1D64F}" => "\\mathsfbfit{T} ", // 𝙏 
        "\u{1D650}" => "\\mathsfbfit{U} ", // 𝙐 
        "\u{1D651}" => "\\mathsfbfit{V} ", // 𝙑 
        "\u{1D652}" => "\\mathsfbfit{W} ", // 𝙒 
        "\u{1D653}" => "\\mathsfbfit{X} ", // 𝙓 
        "\u{1D654}" => "\\mathsfbfit{Y} ", // 𝙔 
        "\u{1D655}" => "\\mathsfbfit{Z} ", // 𝙕 
        "\u{1D656}" => "\\mathsfbfit{a} ", // 𝙖 
        "\u{1D657}" => "\\mathsfbfit{b} ", // 𝙗 
        "\u{1D658}" => "\\mathsfbfit{c} ", // 𝙘 
        "\u{1D659}" => "\\mathsfbfit{d} ", // 𝙙 
        "\u{1D65A}" => "\\mathsfbfit{e} ", // 𝙚 
        "\u{1D65B}" => "\\mathsfbfit{f} ", // 𝙛 
        "\u{1D65C}" => "\\mathsfbfit{g} ", // 𝙜 
        "\u{1D65D}" => "\\mathsfbfit{h} ", // 𝙝 
        "\u{1D65E}" => "\\mathsfbfit{i} ", // 𝙞 
        "\u{1D65F}" => "\\mathsfbfit{j} ", // 𝙟 
        "\u{1D660}" => "\\mathsfbfit{k} ", // 𝙠 
        "\u{1D661}" => "\\mathsfbfit{l} ", // 𝙡 
        "\u{1D662}" => "\\mathsfbfit{m} ", // 𝙢 
        "\u{1D663}" => "\\mathsfbfit{n} ", // 𝙣 
        "\u{1D664}" => "\\mathsfbfit{o} ", // 𝙤 
        "\u{1D665}" => "\\mathsfbfit{p} ", // 𝙥 
        "\u{1D666}" => "\\mathsfbfit{q} ", // 𝙦 
        "\u{1D667}" => "\\mathsfbfit{r} ", // 𝙧 
        "\u{1D668}" => "\\mathsfbfit{s} ", // 𝙨 
        "\u{1D669}" => "\\mathsfbfit{t} ", // 𝙩 
        "\u{1D66A}" => "\\mathsfbfit{u} ", // 𝙪 
        "\u{1D66B}" => "\\mathsfbfit{v} ", // 𝙫 
        "\u{1D66C}" => "\\mathsfbfit{w} ", // 𝙬 
        "\u{1D66D}" => "\\mathsfbfit{x} ", // 𝙭 
        "\u{1D66E}" => "\\mathsfbfit{y} ", // 𝙮 
        "\u{1D66F}" => "\\mathsfbfit{z} ", // 𝙯 
        "\u{1D670}" => "\\mathtt{A} ", // 𝙰 
        "\u{1D671}" => "\\mathtt{B} ", // 𝙱 
        "\u{1D672}" => "\\mathtt{C} ", // 𝙲 
        "\u{1D673}" => "\\mathtt{D} ", // 𝙳 
        "\u{1D674}" => "\\mathtt{E} ", // 𝙴 
        "\u{1D675}" => "\\mathtt{F} ", // 𝙵 
        "\u{1D676}" => "\\mathtt{G} ", // 𝙶 
        "\u{1D677}" => "\\mathtt{H} ", // 𝙷 
        "\u{1D678}" => "\\mathtt{I} ", // 𝙸 
        "\u{1D679}" => "\\mathtt{J} ", // 𝙹 
        "\u{1D67A}" => "\\mathtt{K} ", // 𝙺 
        "\u{1D67B}" => "\\mathtt{L} ", // 𝙻 
        "\u{1D67C}" => "\\mathtt{M} ", // 𝙼 
        "\u{1D67D}" => "\\mathtt{N} ", // 𝙽 
        "\u{1D67E}" => "\\mathtt{O} ", // 𝙾 
        "\u{1D67F}" => "\\mathtt{P} ", // 𝙿 
        "\u{1D680}" => "\\mathtt{Q} ", // 𝚀 
        "\u{1D681}" => "\\mathtt{R} ", // 𝚁 
        "\u{1D682}" => "\\mathtt{S} ", // 𝚂 
        "\u{1D683}" => "\\mathtt{T} ", // 𝚃 
        "\u{1D684}" => "\\mathtt{U} ", // 𝚄 
        "\u{1D685}" => "\\mathtt{V} ", // 𝚅 
        "\u{1D686}" => "\\mathtt{W} ", // 𝚆 
        "\u{1D687}" => "\\mathtt{X} ", // 𝚇 
        "\u{1D688}" => "\\mathtt{Y} ", // 𝚈 
        "\u{1D689}" => "\\mathtt{Z} ", // 𝚉 
        "\u{1D68A}" => "\\mathtt{a} ", // 𝚊 
        "\u{1D68B}" => "\\mathtt{b} ", // 𝚋 
        "\u{1D68C}" => "\\mathtt{c} ", // 𝚌 
        "\u{1D68D}" => "\\mathtt{d} ", // 𝚍 
        "\u{1D68E}" => "\\mathtt{e} ", // 𝚎 
        "\u{1D68F}" => "\\mathtt{f} ", // 𝚏 
        "\u{1D690}" => "\\mathtt{g} ", // 𝚐 
        "\u{1D691}" => "\\mathtt{h} ", // 𝚑 
        "\u{1D692}" => "\\mathtt{i} ", // 𝚒 
        "\u{1D693}" => "\\mathtt{j} ", // 𝚓 
        "\u{1D694}" => "\\mathtt{k} ", // 𝚔 
        "\u{1D695}" => "\\mathtt{l} ", // 𝚕 
        "\u{1D696}" => "\\mathtt{m} ", // 𝚖 
        "\u{1D697}" => "\\mathtt{n} ", // 𝚗 
        "\u{1D698}" => "\\mathtt{o} ", // 𝚘 
        "\u{1D699}" => "\\mathtt{p} ", // 𝚙 
        "\u{1D69A}" => "\\mathtt{q} ", // 𝚚 
        "\u{1D69B}" => "\\mathtt{r} ", // 𝚛 
        "\u{1D69C}" => "\\mathtt{s} ", // 𝚜 
        "\u{1D69D}" => "\\mathtt{t} ", // 𝚝 
        "\u{1D69E}" => "\\mathtt{u} ", // 𝚞 
        "\u{1D69F}" => "\\mathtt{v} ", // 𝚟 
        "\u{1D6A0}" => "\\mathtt{w} ", // 𝚠 
        "\u{1D6A1}" => "\\mathtt{x} ", // 𝚡 
        "\u{1D6A2}" => "\\mathtt{y} ", // 𝚢 
        "\u{1D6A3}" => "\\mathtt{z} ", // 𝚣 
        "\u{1D6A4}" => "\\imath ", // 𝚤 
        "\u{1D6A5}" => "\\jmath ", // 𝚥 
        "\u{1D6AA}" => "\\mathbf{\Gamma} ", // 𝚪 
        "\u{1D6AB}" => "\\mathbf{\Delta} ", // 𝚫 
        "\u{1D6AF}" => "\\mathbf{\Theta} ", // 𝚯 
        "\u{1D6B2}" => "\\mathbf{\Lambda} ", // 𝚲 
        "\u{1D6B5}" => "\\mathbf{\Xi} ", // 𝚵 
        "\u{1D6B7}" => "\\mathbf{\Pi} ", // 𝚷 
        "\u{1D6BA}" => "\\mathbf{\Sigma} ", // 𝚺 
        "\u{1D6BC}" => "\\mathbf{\Upsilon} ", // 𝚼 
        "\u{1D6BD}" => "\\mathbf{\Phi} ", // 𝚽 
        "\u{1D6BF}" => "\\mathbf{\Psi} ", // 𝚿 
        "\u{1D6C0}" => "\\mathbf{\Omega} ", // 𝛀 
        "\u{1D6C2}" => "\\mathbf{\alpha} ", // 𝛂 
        "\u{1D6C3}" => "\\mathbf{\beta} ", // 𝛃 
        "\u{1D6C4}" => "\\mathbf{\gamma} ", // 𝛄 
        "\u{1D6C5}" => "\\mathbf{\delta} ", // 𝛅 
        "\u{1D6C6}" => "\\mathbf{\varepsilon} ", // 𝛆 
        "\u{1D6C7}" => "\\mathbf{\zeta} ", // 𝛇 
        "\u{1D6C8}" => "\\mathbf{\eta} ", // 𝛈 
        "\u{1D6C9}" => "\\mathbf{\theta} ", // 𝛉 
        "\u{1D6CA}" => "\\mathbf{\iota} ", // 𝛊 
        "\u{1D6CB}" => "\\mathbf{\kappa} ", // 𝛋 
        "\u{1D6CC}" => "\\mathbf{\lambda} ", // 𝛌 
        "\u{1D6CD}" => "\\mathbf{\mu} ", // 𝛍 
        "\u{1D6CE}" => "\\mathbf{\nu} ", // 𝛎 
        "\u{1D6CF}" => "\\mathbf{\xi} ", // 𝛏 
        "\u{1D6D1}" => "\\mathbf{\pi} ", // 𝛑 
        "\u{1D6D2}" => "\\mathbf{\rho} ", // 𝛒 
        "\u{1D6D3}" => "\\mathbf{\varsigma} ", // 𝛓 
        "\u{1D6D4}" => "\\mathbf{\sigma} ", // 𝛔 
        "\u{1D6D5}" => "\\mathbf{\tau} ", // 𝛕 
        "\u{1D6D6}" => "\\mathbf{\upsilon} ", // 𝛖 
        "\u{1D6D7}" => "\\mathbf{\varphi} ", // 𝛗 
        "\u{1D6D8}" => "\\mathbf{\chi} ", // 𝛘 
        "\u{1D6D9}" => "\\mathbf{\psi} ", // 𝛙 
        "\u{1D6DA}" => "\\mathbf{\omega} ", // 𝛚 
        "\u{1D6DC}" => "\\mathbf{\epsilon} ", // 𝛜 
        "\u{1D6DD}" => "\\mathbf{\vartheta} ", // 𝛝 
        "\u{1D6DF}" => "\\mathbf{\phi} ", // 𝛟 
        "\u{1D6E0}" => "\\mathbf{\varrho} ", // 𝛠 
        "\u{1D6E1}" => "\\mathbf{\varpi} ", // 𝛡 
        "\u{1D6E4}" => "\\Gamma ", // 𝛤 
        "\u{1D6E5}" => "\\Delta ", // 𝛥 
        "\u{1D6E9}" => "\\Theta ", // 𝛩 
        "\u{1D6EC}" => "\\Lambda ", // 𝛬 
        "\u{1D6EF}" => "\\Xi ", // 𝛯 
        "\u{1D6F1}" => "\\Pi ", // 𝛱 
        "\u{1D6F4}" => "\\Sigma ", // 𝛴 
        "\u{1D6F6}" => "\\Upsilon ", // 𝛶 
        "\u{1D6F7}" => "\\Phi ", // 𝛷 
        "\u{1D6F9}" => "\\Psi ", // 𝛹 
        "\u{1D6FA}" => "\\Omega ", // 𝛺 
        "\u{1D6FC}" => "\\alpha ", // 𝛼 
        "\u{1D6FD}" => "\\beta ", // 𝛽 
        "\u{1D6FE}" => "\\gamma ", // 𝛾 
        "\u{1D6FF}" => "\\delta ", // 𝛿 
        "\u{1D700}" => "\\varepsilon ", // 𝜀 
        "\u{1D701}" => "\\zeta ", // 𝜁 
        "\u{1D702}" => "\\eta ", // 𝜂 
        "\u{1D703}" => "\\theta ", // 𝜃 
        "\u{1D704}" => "\\iota ", // 𝜄 
        "\u{1D705}" => "\\kappa ", // 𝜅 
        "\u{1D706}" => "\\lambda ", // 𝜆 
        "\u{1D707}" => "\\mu ", // 𝜇 
        "\u{1D708}" => "\\nu ", // 𝜈 
        "\u{1D709}" => "\\xi ", // 𝜉 
        "\u{1D70B}" => "\\pi ", // 𝜋 
        "\u{1D70C}" => "\\rho ", // 𝜌 
        "\u{1D70D}" => "\\varsigma ", // 𝜍 
        "\u{1D70E}" => "\\sigma ", // 𝜎 
        "\u{1D70F}" => "\\tau ", // 𝜏 
        "\u{1D710}" => "\\upsilon ", // 𝜐 
        "\u{1D711}" => "\\varphi ", // 𝜑 
        "\u{1D712}" => "\\chi ", // 𝜒 
        "\u{1D713}" => "\\psi ", // 𝜓 
        "\u{1D714}" => "\\omega ", // 𝜔 
        "\u{1D715}" => "\\partial ", // 𝜕 
        "\u{1D716}" => "\\epsilon ", // 𝜖 
        "\u{1D717}" => "\\vartheta ", // 𝜗 
        "\u{1D718}" => "\\varkappa ", // 𝜘 
        "\u{1D719}" => "\\phi ", // 𝜙 
        "\u{1D71A}" => "\\varrho ", // 𝜚 
        "\u{1D71B}" => "\\varpi ", // 𝜛 
        "\u{1D71E}" => "\\mathbfit{\Gamma} ", // 𝜞 
        "\u{1D71F}" => "\\mathbfit{\Delta} ", // 𝜟 
        "\u{1D723}" => "\\mathbfit{\Theta} ", // 𝜣 
        "\u{1D726}" => "\\mathbfit{\Lambda} ", // 𝜦 
        "\u{1D729}" => "\\mathbfit{\Xi} ", // 𝜩 
        "\u{1D72B}" => "\\mathbfit{\Pi} ", // 𝜫 
        "\u{1D72E}" => "\\mathbfit{\Sigma} ", // 𝜮 
        "\u{1D730}" => "\\mathbfit{\Upsilon} ", // 𝜰 
        "\u{1D731}" => "\\mathbfit{\Phi} ", // 𝜱 
        "\u{1D733}" => "\\mathbfit{\Psi} ", // 𝜳 
        "\u{1D734}" => "\\mathbfit{\Omega} ", // 𝜴 
        "\u{1D736}" => "\\mathbfit{\alpha} ", // 𝜶 
        "\u{1D737}" => "\\mathbfit{\beta} ", // 𝜷 
        "\u{1D738}" => "\\mathbfit{\gamma} ", // 𝜸 
        "\u{1D739}" => "\\mathbfit{\delta} ", // 𝜹 
        "\u{1D73A}" => "\\mathbfit{\varepsilon} ", // 𝜺 
        "\u{1D73B}" => "\\mathbfit{\zeta} ", // 𝜻 
        "\u{1D73C}" => "\\mathbfit{\eta} ", // 𝜼 
        "\u{1D73D}" => "\\mathbfit{\theta} ", // 𝜽 
        "\u{1D73E}" => "\\mathbfit{\iota} ", // 𝜾 
        "\u{1D73F}" => "\\mathbfit{\kappa} ", // 𝜿 
        "\u{1D740}" => "\\mathbfit{\lambda} ", // 𝝀 
        "\u{1D741}" => "\\mathbfit{\mu} ", // 𝝁 
        "\u{1D742}" => "\\mathbfit{\nu} ", // 𝝂 
        "\u{1D743}" => "\\mathbfit{\xi} ", // 𝝃 
        "\u{1D745}" => "\\mathbfit{\pi} ", // 𝝅 
        "\u{1D746}" => "\\mathbfit{\rho} ", // 𝝆 
        "\u{1D747}" => "\\mathbfit{\varsigma} ", // 𝝇 
        "\u{1D748}" => "\\mathbfit{\sigma} ", // 𝝈 
        "\u{1D749}" => "\\mathbfit{\tau} ", // 𝝉 
        "\u{1D74A}" => "\\mathbfit{\upsilon} ", // 𝝊 
        "\u{1D74B}" => "\\mathbfit{\varphi} ", // 𝝋 
        "\u{1D74C}" => "\\mathbfit{\chi} ", // 𝝌 
        "\u{1D74D}" => "\\mathbfit{\psi} ", // 𝝍 
        "\u{1D74E}" => "\\mathbfit{\omega} ", // 𝝎 
        "\u{1D750}" => "\\mathbfit{\epsilon} ", // 𝝐 
        "\u{1D751}" => "\\mathbfit{\vartheta} ", // 𝝑 
        "\u{1D753}" => "\\mathbfit{\phi} ", // 𝝓 
        "\u{1D754}" => "\\mathbfit{\varrho} ", // 𝝔 
        "\u{1D755}" => "\\mathbfit{\varpi} ", // 𝝕 
        "\u{1D758}" => "\\mathsfbf{\Gamma} ", // 𝝘 
        "\u{1D759}" => "\\mathsfbf{\Delta} ", // 𝝙 
        "\u{1D75D}" => "\\mathsfbf{\Theta} ", // 𝝝 
        "\u{1D760}" => "\\mathsfbf{\Lambda} ", // 𝝠 
        "\u{1D763}" => "\\mathsfbf{\Xi} ", // 𝝣 
        "\u{1D765}" => "\\mathsfbf{\Pi} ", // 𝝥 
        "\u{1D768}" => "\\mathsfbf{\Sigma} ", // 𝝨 
        "\u{1D76A}" => "\\mathsfbf{\Upsilon} ", // 𝝪 
        "\u{1D76B}" => "\\mathsfbf{\Phi} ", // 𝝫 
        "\u{1D76D}" => "\\mathsfbf{\Psi} ", // 𝝭 
        "\u{1D76E}" => "\\mathsfbf{\Omega} ", // 𝝮 
        "\u{1D770}" => "\\mathsfbf{\alpha} ", // 𝝰 
        "\u{1D771}" => "\\mathsfbf{\beta} ", // 𝝱 
        "\u{1D772}" => "\\mathsfbf{\gamma} ", // 𝝲 
        "\u{1D773}" => "\\mathsfbf{\delta} ", // 𝝳 
        "\u{1D774}" => "\\mathsfbf{\varepsilon} ", // 𝝴 
        "\u{1D775}" => "\\mathsfbf{\zeta} ", // 𝝵 
        "\u{1D776}" => "\\mathsfbf{\eta} ", // 𝝶 
        "\u{1D777}" => "\\mathsfbf{\theta} ", // 𝝷 
        "\u{1D778}" => "\\mathsfbf{\iota} ", // 𝝸 
        "\u{1D779}" => "\\mathsfbf{\kappa} ", // 𝝹 
        "\u{1D77A}" => "\\mathsfbf{\lambda} ", // 𝝺 
        "\u{1D77B}" => "\\mathsfbf{\mu} ", // 𝝻 
        "\u{1D77C}" => "\\mathsfbf{\nu} ", // 𝝼 
        "\u{1D77D}" => "\\mathsfbf{\xi} ", // 𝝽 
        "\u{1D77F}" => "\\mathsfbf{\pi} ", // 𝝿 
        "\u{1D780}" => "\\mathsfbf{\rho} ", // 𝞀 
        "\u{1D781}" => "\\mathsfbf{\varsigma} ", // 𝞁 
        "\u{1D782}" => "\\mathsfbf{\sigma} ", // 𝞂 
        "\u{1D783}" => "\\mathsfbf{\tau} ", // 𝞃 
        "\u{1D784}" => "\\mathsfbf{\upsilon} ", // 𝞄 
        "\u{1D785}" => "\\mathsfbf{\varphi} ", // 𝞅 
        "\u{1D786}" => "\\mathsfbf{\chi} ", // 𝞆 
        "\u{1D787}" => "\\mathsfbf{\psi} ", // 𝞇 
        "\u{1D788}" => "\\mathsfbf{\omega} ", // 𝞈 
        "\u{1D78A}" => "\\mathsfbf{\epsilon} ", // 𝞊 
        "\u{1D78B}" => "\\mathsfbf{\vartheta} ", // 𝞋 
        "\u{1D78D}" => "\\mathsfbf{\phi} ", // 𝞍 
        "\u{1D78E}" => "\\mathsfbf{\varrho} ", // 𝞎 
        "\u{1D78F}" => "\\mathsfbf{\varpi} ", // 𝞏 
        "\u{1D792}" => "\\mathsfbfit{\Gamma} ", // 𝞒 
        "\u{1D793}" => "\\mathsfbfit{\Delta} ", // 𝞓 
        "\u{1D797}" => "\\mathsfbfit{\Theta} ", // 𝞗 
        "\u{1D79A}" => "\\mathsfbfit{\Lambda} ", // 𝞚 
        "\u{1D79D}" => "\\mathsfbfit{\Xi} ", // 𝞝 
        "\u{1D79F}" => "\\mathsfbfit{\Pi} ", // 𝞟 
        "\u{1D7A2}" => "\\mathsfbfit{\Sigma} ", // 𝞢 
        "\u{1D7A4}" => "\\mathsfbfit{\Upsilon} ", // 𝞤 
        "\u{1D7A5}" => "\\mathsfbfit{\Phi} ", // 𝞥 
        "\u{1D7A7}" => "\\mathsfbfit{\Psi} ", // 𝞧 
        "\u{1D7A8}" => "\\mathsfbfit{\Omega} ", // 𝞨 
        "\u{1D7AA}" => "\\mathsfbfit{\alpha} ", // 𝞪 
        "\u{1D7AB}" => "\\mathsfbfit{\beta} ", // 𝞫 
        "\u{1D7AC}" => "\\mathsfbfit{\gamma} ", // 𝞬 
        "\u{1D7AD}" => "\\mathsfbfit{\delta} ", // 𝞭 
        "\u{1D7AE}" => "\\mathsfbfit{\varepsilon} ", // 𝞮 
        "\u{1D7AF}" => "\\mathsfbfit{\zeta} ", // 𝞯 
        "\u{1D7B0}" => "\\mathsfbfit{\eta} ", // 𝞰 
        "\u{1D7B1}" => "\\mathsfbfit{\theta} ", // 𝞱 
        "\u{1D7B2}" => "\\mathsfbfit{\iota} ", // 𝞲 
        "\u{1D7B3}" => "\\mathsfbfit{\kappa} ", // 𝞳 
        "\u{1D7B4}" => "\\mathsfbfit{\lambda} ", // 𝞴 
        "\u{1D7B5}" => "\\mathsfbfit{\mu} ", // 𝞵 
        "\u{1D7B6}" => "\\mathsfbfit{\nu} ", // 𝞶 
        "\u{1D7B7}" => "\\mathsfbfit{\xi} ", // 𝞷 
        "\u{1D7B9}" => "\\mathsfbfit{\pi} ", // 𝞹 
        "\u{1D7BA}" => "\\mathsfbfit{\rho} ", // 𝞺 
        "\u{1D7BB}" => "\\mathsfbfit{\varsigma} ", // 𝞻 
        "\u{1D7BC}" => "\\mathsfbfit{\sigma} ", // 𝞼 
        "\u{1D7BD}" => "\\mathsfbfit{\tau} ", // 𝞽 
        "\u{1D7BE}" => "\\mathsfbfit{\upsilon} ", // 𝞾 
        "\u{1D7BF}" => "\\mathsfbfit{\varphi} ", // 𝞿 
        "\u{1D7C0}" => "\\mathsfbfit{\chi} ", // 𝟀 
        "\u{1D7C1}" => "\\mathsfbfit{\psi} ", // 𝟁 
        "\u{1D7C2}" => "\\mathsfbfit{\omega} ", // 𝟂 
        "\u{1D7C4}" => "\\mathsfbfit{\epsilon} ", // 𝟄 
        "\u{1D7C5}" => "\\mathsfbfit{\vartheta} ", // 𝟅 
        "\u{1D7C7}" => "\\mathsfbfit{\phi} ", // 𝟇 
        "\u{1D7C8}" => "\\mathsfbfit{\varrho} ", // 𝟈 
        "\u{1D7C9}" => "\\mathsfbfit{\varpi} ", // 𝟉 
        "\u{1D7CE}" => "\\mathbf{0} ", // 𝟎 
        "\u{1D7CF}" => "\\mathbf{1} ", // 𝟏 
        "\u{1D7D0}" => "\\mathbf{2} ", // 𝟐 
        "\u{1D7D1}" => "\\mathbf{3} ", // 𝟑 
        "\u{1D7D2}" => "\\mathbf{4} ", // 𝟒 
        "\u{1D7D3}" => "\\mathbf{5} ", // 𝟓 
        "\u{1D7D4}" => "\\mathbf{6} ", // 𝟔 
        "\u{1D7D5}" => "\\mathbf{7} ", // 𝟕 
        "\u{1D7D6}" => "\\mathbf{8} ", // 𝟖 
        "\u{1D7D7}" => "\\mathbf{9} ", // 𝟗 
        "\u{1D7D8}" => "\\mathbb{0} ", // 𝟘 
        "\u{1D7D9}" => "\\mathbb{1} ", // 𝟙 
        "\u{1D7DA}" => "\\mathbb{2} ", // 𝟚 
        "\u{1D7DB}" => "\\mathbb{3} ", // 𝟛 
        "\u{1D7DC}" => "\\mathbb{4} ", // 𝟜 
        "\u{1D7DD}" => "\\mathbb{5} ", // 𝟝 
        "\u{1D7DE}" => "\\mathbb{6} ", // 𝟞 
        "\u{1D7DF}" => "\\mathbb{7} ", // 𝟟 
        "\u{1D7E0}" => "\\mathbb{8} ", // 𝟠 
        "\u{1D7E1}" => "\\mathbb{9} ", // 𝟡 
        "\u{1D7E2}" => "\\mathsf{0} ", // 𝟢 
        "\u{1D7E3}" => "\\mathsf{1} ", // 𝟣 
        "\u{1D7E4}" => "\\mathsf{2} ", // 𝟤 
        "\u{1D7E5}" => "\\mathsf{3} ", // 𝟥 
        "\u{1D7E6}" => "\\mathsf{4} ", // 𝟦 
        "\u{1D7E7}" => "\\mathsf{5} ", // 𝟧 
        "\u{1D7E8}" => "\\mathsf{6} ", // 𝟨 
        "\u{1D7E9}" => "\\mathsf{7} ", // 𝟩 
        "\u{1D7EA}" => "\\mathsf{8} ", // 𝟪 
        "\u{1D7EB}" => "\\mathsf{9} ", // 𝟫 
        "\u{1D7EC}" => "\\mathsfbf{0} ", // 𝟬 
        "\u{1D7ED}" => "\\mathsfbf{1} ", // 𝟭 
        "\u{1D7EE}" => "\\mathsfbf{2} ", // 𝟮 
        "\u{1D7EF}" => "\\mathsfbf{3} ", // 𝟯 
        "\u{1D7F0}" => "\\mathsfbf{4} ", // 𝟰 
        "\u{1D7F1}" => "\\mathsfbf{5} ", // 𝟱 
        "\u{1D7F2}" => "\\mathsfbf{6} ", // 𝟲 
        "\u{1D7F3}" => "\\mathsfbf{7} ", // 𝟳 
        "\u{1D7F4}" => "\\mathsfbf{8} ", // 𝟴 
        "\u{1D7F5}" => "\\mathsfbf{9} ", // 𝟵 
        "\u{1D7F6}" => "\\mathtt{0} ", // 𝟶 
        "\u{1D7F7}" => "\\mathtt{1} ", // 𝟷 
        "\u{1D7F8}" => "\\mathtt{2} ", // 𝟸 
        "\u{1D7F9}" => "\\mathtt{3} ", // 𝟹 
        "\u{1D7FA}" => "\\mathtt{4} ", // 𝟺 
        "\u{1D7FB}" => "\\mathtt{5} ", // 𝟻 
        "\u{1D7FC}" => "\\mathtt{6} ", // 𝟼 
        "\u{1D7FD}" => "\\mathtt{7} ", // 𝟽 
        "\u{1D7FE}" => "\\mathtt{8} ", // 𝟾 
        "\u{1D7FF}" => "\\mathtt{9} ", // 𝟿 
    ];

}
